/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-22 12:31:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>ASSISTIFY - Digital Personal Assistant</title>\n");
      out.write("    <!-- Bootstrap 5.0.2 CDN -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Space+Grotesk' rel='stylesheet'>\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"container-fluid bg-white py-3 border-bottom\">\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <a href=\"index.jsp\">\n");
      out.write("                    <img src=\"assets/Logo.png\" alt=\"ASSISTIFY Logo\" class=\"img-fluid\" style=\"width: 150px;\">\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <nav class=\"ms-auto\">\n");
      out.write("                <ul class=\"nav\">\n");
      out.write("                    <li class=\"nav-item\"><a href=\"#\" class=\"nav-link text-danger\">About us</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a href=\"#\" class=\"nav-link text-danger\">Services</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a href=\"#\" class=\"nav-link text-danger\">Use Cases</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a href=\"#\" class=\"nav-link text-danger\">Feature</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a href=\"login_page.jsp\" class=\"nav-link text-danger border border-danger rounded-3 px-4\">Log In</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <section class=\"hero bg-white py-5\">\n");
      out.write("        <div class=\"container d-flex justify-content-between align-items-center\">\n");
      out.write("            <div class=\"hero-text\" style=\"max-width: 50%;\">\n");
      out.write("                <h1 class=\"text-danger fs-1\">Manage your day with your very own digital personal assistant</h1>\n");
      out.write("                <p class=\"fs-4 text-dark mt-4\">Our application helps people grow and succeed with their lives through digital personal assistant. We help people manage their daily, works, schedule, etc.</p>\n");
      out.write("                <a href=\"registration_page.jsp\" class=\"btn btn-danger btn-lg mt-4\">Get Started Now</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"hero-icons\">\n");
      out.write("                <img src=\"assets/DashboardImage.png\" alt=\"Icons Set\" class=\"img-fluid\" style=\"max-width: 500px;\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section class=\"features py-5\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2 class=\"text-center text-white bg-danger p-2 rounded-3\">Features</h2>\n");
      out.write("        <div class=\"feature-boxes mt-4\">\n");
      out.write("            <div class=\"feature-box1\">\n");
      out.write("                <div class=\"feature-content text-center\">\n");
      out.write("                    <h3 class=\"text-white\">Note and Voice Note</h3>\n");
      out.write("                    <div style=\"display: flex; justify-content: right;\">\n");
      out.write("                        <img src=\"assets/IconNote.png\" alt=\"Note Icon\" class=\"img-fluid\" style=\"max-width: 150px;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display: flex; align-items: center; gap: 8px;\">\n");
      out.write("                        <img src=\"assets/LogoPanah1.png\" alt=\"Arrow Logo\" style=\"width: 40px; height: auto;\">\n");
      out.write("                        <a href=\"#\" class=\"text-danger\">Learn more</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"feature-box2\">\n");
      out.write("                <div class=\"feature-content text-center\">\n");
      out.write("                    <h3>To-Do List</h3>\n");
      out.write("                    <div style=\"display: flex; justify-content: right;\">\n");
      out.write("                        <img src=\"assets/IconToDo.png\" alt=\"To-Do List Icon\" class=\"img-fluid\" style=\"max-width: 150px;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display: flex; align-items: center; gap: 8px;\">\n");
      out.write("                        <img src=\"assets/LogoPanah2.png\" alt=\"Arrow Logo\" style=\"width: 40px; height: auto;\">\n");
      out.write("                        <a href=\"#\" class=\"text-white\">Learn more</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"feature-box2 mt-4\">\n");
      out.write("                <div class=\"feature-content text-center\">\n");
      out.write("                    <h3>Daily Reminder</h3>\n");
      out.write("                    <div style=\"display: flex; justify-content: right;\">\n");
      out.write("                        <img src=\"assets/IconReminder.png\" alt=\"Reminder Icon\" class=\"img-fluid\" style=\"max-width: 150px;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display: flex; align-items: center; gap: 8px;\">\n");
      out.write("                        <img src=\"assets/LogoPanah2.png\" alt=\"Arrow Logo\" style=\"width: 40px; height: auto;\">\n");
      out.write("                        <a href=\"#\" class=\"text-white\">Learn more</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"feature-box1 mt-4\">\n");
      out.write("                <div class=\"feature-content text-center\">\n");
      out.write("                    <h3 class=\"text-white\">Alarm Clock</h3>\n");
      out.write("                    <div style=\"display: flex; justify-content: right;\">\n");
      out.write("                        <img src=\"assets/IconAlarm.png\" alt=\"Alarm Icon\" class=\"img-fluid\" style=\"max-width: 150px;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"display: flex; align-items: center; gap: 8px;\">\n");
      out.write("                        <img src=\"assets/LogoPanah1.png\" alt=\"Arrow Logo\" style=\"width: 40px; height: auto;\">\n");
      out.write("                        <a href=\"#\" class=\"text-danger\">Learn more</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <footer class=\"bg-danger text-white text-center py-4\">\n");
      out.write("        <p>&copy; 2025 Assistify. All rights reserved.</p>\n");
      out.write("        <p>Powered by <a href=\"#\" class=\"text-white text-decoration-none klik\">Assistify Technologies</a></p>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka9H3GMh7dQssI40c5n8O11Fpb0pSQZxQSTH5tf9QmjAcqfOgnMw2uZxtFsiqgdF\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
