/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-12 19:41:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Alarm;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;

public final class alarm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("model.Alarm");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fa-solid fa-clock-rotate-left\"></i>\r\n");
      out.write("            Alarms\r\n");
      out.write("        </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "User" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");

@SuppressWarnings("unchecked")
List<Alarm> alarmList = (List<Alarm>) request.getAttribute("alarmList");
if (alarmList != null && !alarmList.isEmpty()) {

      out.write("\r\n");
      out.write("    <div class=\"alarm-grid\">\r\n");
      out.write("    ");

        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, dd MMM yyyy");
        for (Alarm alarm : alarmList) {
    
      out.write("\r\n");
      out.write("        <div class=\"alarm-card\">\r\n");
      out.write("            <div class=\"action-buttons\">\r\n");
      out.write("                <button class=\"action-btn edit-btn\" onclick=\"editAlarm(");
      out.print( alarm.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( alarm.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( alarm.getTimeAsDateTime() );
      out.write("', '");
      out.print( alarm.getStatus() );
      out.write("')\">\r\n");
      out.write("                    <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"action-btn delete-btn\" onclick=\"deleteAlarm(");
      out.print( alarm.getId() );
      out.write(")\">\r\n");
      out.write("                    <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"alarm-title\">");
      out.print( alarm.getTitle() );
      out.write("</div>\r\n");
      out.write("            <div class=\"alarm-time\">");
      out.print( timeFormat.format(alarm.getTime()) );
      out.write("</div>\r\n");
      out.write("            <div class=\"alarm-date\">");
      out.print( dateFormat.format(alarm.getTime()) );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("    </div>\r\n");

} else {

      out.write("\r\n");
      out.write("    <div class=\"empty-state\">\r\n");
      out.write("        <i class=\"fas fa-clock fa-3x mb-3\"></i>\r\n");
      out.write("        <h3>No alarms set</h3>\r\n");
      out.write("        <p>Add your first alarm to get started!</p>\r\n");
      out.write("        <button class=\"btn btn-primary btn-lg\" onclick=\"showAddAlarmModal()\">\r\n");
      out.write("            <i class=\"fas fa-plus\"></i> Add Your First Alarm\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Floating Add Button -->\r\n");
      out.write("<button class=\"floating-add-btn\" onclick=\"showAddAlarmModal()\">\r\n");
      out.write("    <i class=\"fas fa-plus\"></i>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Alarm Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addAlarmModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add New Alarm\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"AddAlarmServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addAlarmTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"addAlarmTitle\" name=\"title\" placeholder=\"e.g. Wake up\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addAlarmTime\" class=\"form-label\">Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"addAlarmTime\" name=\"time\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Add Alarm</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Alarm Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editAlarmModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-edit\"></i> Edit Alarm\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditAlarmServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"editAlarmId\" name=\"id\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editAlarmTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editAlarmTitle\" name=\"title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editAlarmTime\" class=\"form-label\">Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"editAlarmTime\" name=\"time\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editAlarmStatus\" class=\"form-label\">Status</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"editAlarmStatus\" name=\"status\" required>\r\n");
      out.write("                            <option value=\"active\">Active</option>\r\n");
      out.write("                            <option value=\"inactive\">Inactive</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Save Changes</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function showAddAlarmModal() {\r\n");
      out.write("    // Set default time to current time\r\n");
      out.write("    const now = new Date();\r\n");
      out.write("    now.setMinutes(now.getMinutes() - now.getTimezoneOffset());\r\n");
      out.write("    document.getElementById('addAlarmTime').value = now.toISOString().slice(0, 16);\r\n");
      out.write("    \r\n");
      out.write("    new bootstrap.Modal(document.getElementById('addAlarmModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editAlarm(id, title, time, status) {\r\n");
      out.write("    document.getElementById('editAlarmId').value = id;\r\n");
      out.write("    document.getElementById('editAlarmTitle').value = title;\r\n");
      out.write("    document.getElementById('editAlarmTime').value = time.replace(' ', 'T').substring(0, 16);\r\n");
      out.write("    document.getElementById('editAlarmStatus').value = status;\r\n");
      out.write("    new bootstrap.Modal(document.getElementById('editAlarmModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteAlarm(id) {\r\n");
      out.write("    Swal.fire({\r\n");
      out.write("        title: 'Are you sure?',\r\n");
      out.write("        text: \"You won't be able to revert this!\",\r\n");
      out.write("        icon: 'warning',\r\n");
      out.write("        showCancelButton: true,\r\n");
      out.write("        confirmButtonColor: '#dc3545',\r\n");
      out.write("        cancelButtonColor: '#6c757d',\r\n");
      out.write("        confirmButtonText: 'Yes, delete it!'\r\n");
      out.write("    }).then((result) => {\r\n");
      out.write("        if (result.isConfirmed) {\r\n");
      out.write("            window.location.href = 'DeleteAlarmServlet?id=' + id;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
