/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-14 07:31:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.*;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Calendar;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Get data from HomeServlet
    @SuppressWarnings("unchecked")
    List<ToDoItem> recentTodos = (List<ToDoItem>) request.getAttribute("recentTodos");
    @SuppressWarnings("unchecked")
    List<Activity> recentActivities = (List<Activity>) request.getAttribute("recentActivities");
    @SuppressWarnings("unchecked")
    List<Alarm> recentAlarms = (List<Alarm>) request.getAttribute("recentAlarms");
    @SuppressWarnings("unchecked")
    List<Reminder> recentReminders = (List<Reminder>) request.getAttribute("recentReminders");
    @SuppressWarnings("unchecked")
    List<TextNote> recentTextNotes = (List<TextNote>) request.getAttribute("recentTextNotes");
    @SuppressWarnings("unchecked")
    List<VoiceNote> recentVoiceNotes = (List<VoiceNote>) request.getAttribute("recentVoiceNotes");
    @SuppressWarnings("unchecked")
    List<JournalEntry> recentJournals = (List<JournalEntry>) request.getAttribute("recentJournals");
    @SuppressWarnings("unchecked")
    List<Reminder> activeReminders = (List<Reminder>) request.getAttribute("activeReminders");
    
    // Get current time for greeting
    Calendar cal = Calendar.getInstance();
    int hour = cal.get(Calendar.HOUR_OF_DAY);
    String greeting;
    if (hour < 12) {
        greeting = "Good Morning";
    } else if (hour < 17) {
        greeting = "Good Afternoon";
    } else {
        greeting = "Good Evening";
    }
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM dd, yyyy");
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    String currentDate = dateFormat.format(new Date());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-home\"></i>\r\n");
      out.write("            ");
      out.print( greeting );
      out.write(',');
      out.write(' ');
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "Guest" );
      out.write("!\r\n");
      out.write("        </h1>\r\n");
      out.write("        <p class=\"text-light\">Welcome back to your digital assistant</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "Guest" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>         \r\n");
      out.write("    \r\n");
      out.write("<!-- Statistics Overview -->\r\n");
      out.write("<div class=\"dashboard-grid\">\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fas fa-chart-line\"></i>\r\n");
      out.write("                Overview\r\n");
      out.write("            </h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row text-center\">\r\n");
      out.write("            <div class=\"col-6 mb-3\">\r\n");
      out.write("                <h2 class=\"text-primary\">");
      out.print( (recentTodos != null ? recentTodos.size() : 0) + (recentActivities != null ? recentActivities.size() : 0) );
      out.write("</h2>\r\n");
      out.write("                <small>Total Tasks</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 mb-3\">\r\n");
      out.write("                <h2 class=\"text-success\">");
      out.print( recentAlarms != null ? recentAlarms.size() : 0 );
      out.write("</h2>\r\n");
      out.write("                <small>Active Alarms</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6\">\r\n");
      out.write("                <h2 class=\"text-warning\">");
      out.print( activeReminders != null ? activeReminders.size() : 0 );
      out.write("</h2>\r\n");
      out.write("                <small>Pending Reminders</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6\">\r\n");
      out.write("                <h2 class=\"text-info\">");
      out.print( recentJournals != null ? recentJournals.size() : 0 );
      out.write("</h2>\r\n");
      out.write("                <small>Journal Entries</small>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- To-Do Items Card -->\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fas fa-tasks\"></i>\r\n");
      out.write("                Recent To-Do Items\r\n");
      out.write("            </h3>\r\n");
      out.write("            <a href=\"TaskServlet\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                View All <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-content\">\r\n");
      out.write("            ");
 if (recentTodos != null && !recentTodos.isEmpty()) { 
      out.write("\r\n");
      out.write("                ");
 for (int i = 0; i < Math.min(5, recentTodos.size()); i++) { 
                    ToDoItem todo = recentTodos.get(i);
                    String statusClass = todo.isCompleted() ? "status-completed" : 
                                       (todo.getDueDate() != null && todo.getDueDate().before(new Date()) ? "status-overdue" : "status-pending");
                    String statusText = todo.isCompleted() ? "Completed" : 
                                      (todo.getDueDate() != null && todo.getDueDate().before(new Date()) ? "Overdue" : "Pending");
                
      out.write("\r\n");
      out.write("                    <div class=\"item-row\">\r\n");
      out.write("                        <div class=\"item-info\">\r\n");
      out.write("                            <div class=\"item-title\">");
      out.print( todo.getTitle() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"item-subtitle\">\r\n");
      out.write("                                ");
 if (todo.getDueDate() != null) { 
      out.write("\r\n");
      out.write("                                    Due: ");
      out.print( new SimpleDateFormat("MMM dd, yyyy").format(todo.getDueDate()) );
      out.write("\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    No due date\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-status\">\r\n");
      out.write("                            <span class=\"status-badge ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( statusText );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"empty-section\">\r\n");
      out.write("                    <i class=\"fas fa-tasks fa-2x\"></i>\r\n");
      out.write("                    <p>No to-do items yet</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Activities Card -->\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                Recent Activities\r\n");
      out.write("            </h3>\r\n");
      out.write("            <a href=\"TaskServlet\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                View All <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-content\">\r\n");
      out.write("            ");
 if (recentActivities != null && !recentActivities.isEmpty()) { 
      out.write("\r\n");
      out.write("                ");
 for (int i = 0; i < Math.min(5, recentActivities.size()); i++) { 
                    Activity activity = recentActivities.get(i);
                
      out.write("\r\n");
      out.write("                    <div class=\"item-row\">\r\n");
      out.write("                        <div class=\"item-info\">\r\n");
      out.write("                            <div class=\"item-title\">");
      out.print( activity.getTitle() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"item-subtitle\">\r\n");
      out.write("                                ");
 if (activity.getStartTime() != null) { 
      out.write("\r\n");
      out.write("                                    Started: ");
      out.print( new SimpleDateFormat("MMM dd, HH:mm").format(activity.getStartTime()) );
      out.write("\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    No start time\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"empty-section\">\r\n");
      out.write("                    <i class=\"fas fa-running fa-2x\"></i>\r\n");
      out.write("                    <p>No activities yet</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Alarms Card -->\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fa-solid fa-clock-rotate-left\"></i>\r\n");
      out.write("                Recent Alarms\r\n");
      out.write("            </h3>\r\n");
      out.write("            <a href=\"AlarmServlet\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                View All <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-content\">\r\n");
      out.write("            ");
 if (recentAlarms != null && !recentAlarms.isEmpty()) { 
      out.write("\r\n");
      out.write("                ");
 for (int i = 0; i < Math.min(5, recentAlarms.size()); i++) { 
                    Alarm alarm = recentAlarms.get(i);
                    String alarmStatus = alarm.getStatus();
                    String statusClass = alarmStatus.equalsIgnoreCase("active") ? "status-active" : "status-pending";
                    String statusText = alarmStatus.equalsIgnoreCase("active") ? "Active" : "Inactive";
                
      out.write("\r\n");
      out.write("                    <div class=\"item-row\">\r\n");
      out.write("                        <div class=\"item-info\">\r\n");
      out.write("                            <div class=\"item-title\">\r\n");
      out.write("                                ");
      out.print( alarm.getTitle() != null ? alarm.getTitle() : "Alarm" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item-subtitle\">\r\n");
      out.write("                                ");
      out.print( new SimpleDateFormat("HH:mm").format(alarm.getTime()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-status\">\r\n");
      out.write("                            <span class=\"status-badge ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( statusText );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"empty-section\">\r\n");
      out.write("                    <i class=\"fa-solid fa-clock-rotate-left fa-2x\"></i>\r\n");
      out.write("                    <p>No alarms set</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Text Notes Card -->\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fas fa-sticky-note\"></i>\r\n");
      out.write("                Recent Text Notes\r\n");
      out.write("            </h3>\r\n");
      out.write("            <a href=\"NoteServlet\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                View All <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-content\">\r\n");
      out.write("            ");
 if (recentTextNotes != null && !recentTextNotes.isEmpty()) { 
      out.write("\r\n");
      out.write("                ");
 for (int i = 0; i < Math.min(5, recentTextNotes.size()); i++) { 
                    TextNote note = recentTextNotes.get(i);
                
      out.write("\r\n");
      out.write("                    <div class=\"item-row\">\r\n");
      out.write("                        <div class=\"item-info\">\r\n");
      out.write("                            <div class=\"item-title\">");
      out.print( note.getTitle() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"item-subtitle\">\r\n");
      out.write("                                ");
      out.print( note.getTextNote().length() > 50 ? 
                                    note.getTextNote().substring(0, 50) + "..." : 
                                    note.getTextNote() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-status\">\r\n");
      out.write("                            <div class=\"time-info\">\r\n");
      out.write("                                ");
      out.print( new SimpleDateFormat("MMM dd").format(note.getCreatedDate()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"empty-section\">\r\n");
      out.write("                    <i class=\"fas fa-sticky-note fa-2x\"></i>\r\n");
      out.write("                    <p>No text notes yet</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Voice Notes Card -->\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fas fa-microphone\"></i>\r\n");
      out.write("                Recent Voice Notes\r\n");
      out.write("            </h3>\r\n");
      out.write("            <a href=\"NoteServlet\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                View All <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-content\">\r\n");
      out.write("            ");
 if (recentVoiceNotes != null && !recentVoiceNotes.isEmpty()) { 
      out.write("\r\n");
      out.write("                ");
 for (int i = 0; i < Math.min(5, recentVoiceNotes.size()); i++) { 
                    VoiceNote note = recentVoiceNotes.get(i);
                
      out.write("\r\n");
      out.write("                    <div class=\"item-row\">\r\n");
      out.write("                        <div class=\"item-info\">\r\n");
      out.write("                            <div class=\"item-title\">");
      out.print( note.getTitle() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"item-subtitle\">\r\n");
      out.write("                                <i class=\"fas fa-volume-up\"></i> Voice recording\r\n");
      out.write("                                ");
 if (note.getVoiceNote() != null && !note.getVoiceNote().isEmpty()) { 
      out.write("\r\n");
      out.write("                                    <audio controls class=\"audio-player mt-2\" style=\"width: 100%; height: 30px;\">\r\n");
      out.write("                                        <source src=\"");
      out.print( note.getVoiceNote() );
      out.write("\" type=\"audio/mpeg\">\r\n");
      out.write("                                        Your browser does not support the audio element.\r\n");
      out.write("                                    </audio>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-status\">\r\n");
      out.write("                            <div class=\"time-info\">\r\n");
      out.write("                                ");
      out.print( new SimpleDateFormat("MMM dd").format(note.getCreatedDate()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"empty-section\">\r\n");
      out.write("                    <i class=\"fas fa-microphone fa-2x\"></i>\r\n");
      out.write("                    <p>No voice notes yet</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Journal Entries Card -->\r\n");
      out.write("    <div class=\"dashboard-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h3 class=\"card-title\">\r\n");
      out.write("                <i class=\"fas fa-book\"></i>\r\n");
      out.write("                Recent Journal Entries\r\n");
      out.write("            </h3>\r\n");
      out.write("            <a href=\"JournalEntryServlet\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("                View All <i class=\"fas fa-arrow-right\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-content\">\r\n");
      out.write("            ");
 if (recentJournals != null && !recentJournals.isEmpty()) { 
      out.write("\r\n");
      out.write("                ");
 for (int i = 0; i < Math.min(5, recentJournals.size()); i++) { 
                    JournalEntry journal = recentJournals.get(i);
                
      out.write("\r\n");
      out.write("                    <div class=\"item-row\">\r\n");
      out.write("                        <div class=\"item-info\">\r\n");
      out.write("                            <div class=\"item-title\">");
      out.print( journal.getTitle() != null ? journal.getTitle() : "Journal Entry" );
      out.write("</div>\r\n");
      out.write("                            <div class=\"item-subtitle\">\r\n");
      out.write("                                ");
      out.print( journal.getContent().length() > 60 ? 
                                    journal.getContent().substring(0, 60) + "..." : 
                                    journal.getContent() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-status\">\r\n");
      out.write("                            <div class=\"time-info\">\r\n");
      out.write("                                ");
      out.print( new SimpleDateFormat("MMM dd").format(journal.getEntrydate()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <div class=\"empty-section\">\r\n");
      out.write("                    <i class=\"fas fa-book fa-2x\"></i>\r\n");
      out.write("                    <p>No journal entries yet</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Quick Actions -->\r\n");
      out.write("<div class=\"dashboard-card\">\r\n");
      out.write("    <div class=\"card-header\">\r\n");
      out.write("        <h3 class=\"card-title\">\r\n");
      out.write("            <i class=\"fas fa-bolt\"></i>\r\n");
      out.write("            Quick Actions\r\n");
      out.write("        </h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-2 col-6 mb-3\">\r\n");
      out.write("            <a href=\"TaskServlet\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                <i class=\"fas fa-tasks d-block mb-2\"></i>\r\n");
      out.write("                Tasks\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2 col-6 mb-3\">\r\n");
      out.write("            <a href=\"AlarmServlet\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                <i class=\"fa-solid fa-clock-rotate-left d-block mb-2\"></i>\r\n");
      out.write("                Alarms\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2 col-6 mb-3\">\r\n");
      out.write("            <a href=\"NoteServlet\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                <i class=\"fas fa-sticky-note d-block mb-2\"></i>\r\n");
      out.write("                Notes\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2 col-6 mb-3\">\r\n");
      out.write("            <a href=\"JournalEntryServlet\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                <i class=\"fas fa-book d-block mb-2\"></i>\r\n");
      out.write("                Journal\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2 col-6 mb-3\">\r\n");
      out.write("            <a href=\"ReminderServlet\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                <i class=\"fas fa-bell d-block mb-2\"></i>\r\n");
      out.write("                Reminders\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2 col-6 mb-3\">\r\n");
      out.write("            <a href=\"HomeServlet?page=settings\" class=\"btn btn-primary w-100\">\r\n");
      out.write("                <i class=\"fas fa-cog d-block mb-2\"></i>\r\n");
      out.write("                Settings\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Update current time every second\r\n");
      out.write("function updateTime() {\r\n");
      out.write("    const now = new Date();\r\n");
      out.write("    const timeString = now.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});\r\n");
      out.write("    const timeElement = document.getElementById('currentTime');\r\n");
      out.write("    if (timeElement) {\r\n");
      out.write("        timeElement.textContent = timeString;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Update time immediately and then every second\r\n");
      out.write("updateTime();\r\n");
      out.write("setInterval(updateTime, 1000);\r\n");
      out.write("\r\n");
      out.write("// Add smooth animations to cards\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const cards = document.querySelectorAll('.dashboard-card');\r\n");
      out.write("    cards.forEach((card, index) => {\r\n");
      out.write("        card.style.opacity = '0';\r\n");
      out.write("        card.style.transform = 'translateY(20px)';\r\n");
      out.write("        \r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            card.style.transition = 'all 0.6s ease';\r\n");
      out.write("            card.style.opacity = '1';\r\n");
      out.write("            card.style.transform = 'translateY(0)';\r\n");
      out.write("        }, index * 100);\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
