/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-13 07:41:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.*;
import java.text.SimpleDateFormat;
import config.DB;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Calendar;

public final class home_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("config.DB");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Digital Assistant</title>\r\n");
      out.write("    <!-- Bootstrap 5.0.2 CDN -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- Google Fonts - Montserrat -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome for icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <!-- SweetAlert2 -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>   \r\n");
      out.write("    ");

    // Get user notification settings
    Integer userIdObj = (Integer) session.getAttribute("userId");
    if (userIdObj == null) {
        response.sendRedirect("login_page.jsp");
        return;
    }
    int userId = userIdObj.intValue();
    
    DB db = new DB();
    db.connect();
    
    int alarmSound = 1;
    int notificationSound = 1;
    
    try {
        // Get alarm sound setting
        String alarmQuery = "SELECT sound FROM notification_settings WHERE user_id = " + userId + " AND type = 'Alarm'";
        ResultSet alarmRs = db.getData(alarmQuery);
        if (alarmRs != null && alarmRs.next()) {
            alarmSound = alarmRs.getInt("sound");
        }
        
        // Get notification sound setting
        String notifQuery = "SELECT sound FROM notification_settings WHERE user_id = " + userId + " AND type = 'Notification'";
        ResultSet notifRs = db.getData(notifQuery);
        if (notifRs != null && notifRs.next()) {
            notificationSound = notifRs.getInt("sound");
        }
    } catch (Exception e) {
        System.err.println("Error getting notification settings: " + e.getMessage());
    } finally {
        db.disconnect();
    }
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Hidden data for JavaScript -->\r\n");
      out.write("    <div id=\"notificationData\" \r\n");
      out.write("         data-user-id=\"");
      out.print( userId );
      out.write("\"\r\n");
      out.write("         data-alarm-sound=\"");
      out.print( alarmSound );
      out.write("\"\r\n");
      out.write("         data-notification-sound=\"");
      out.print( notificationSound );
      out.write("\"\r\n");
      out.write("         style=\"display: none;\"></div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Audio elements for notifications -->\r\n");
      out.write("    <audio id=\"alarmAudio\" preload=\"none\"></audio>\r\n");
      out.write("    <audio id=\"notificationAudio\" preload=\"none\"></audio>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <!-- Add Button at the top -->\r\n");
      out.write("        <!-- <a href=\"#\" class=\"nav-link\" onclick=\"showAddModal()\">\r\n");
      out.write("            <img src=\"assets/image/LogoAdd.png\" alt=\"Add\" class=\"sidebar-icon\" id=\"add-icon\">\r\n");
      out.write("        </a> -->\r\n");
      out.write("            \r\n");
      out.write("        <a href=\"HomeServlet\" class=\"nav-link ");
      out.print( (request.getParameter("page") == null || "home".equals(request.getParameter("page"))) ? "active" : "" );
      out.write("\">\r\n");
      out.write("            <img src=\"assets/image/LogoHome.png\" alt=\"Home\" class=\"sidebar-icon\" id=\"home-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"AlarmServlet\" class=\"nav-link ");
      out.print( ("alarm".equals(request.getParameter("page"))) ? "active" : "" );
      out.write("\">\r\n");
      out.write("            <img src=\"assets/image/LogoAlarm.png\" alt=\"Alarm\" class=\"sidebar-icon\" id=\"alarm-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"ReminderServlet\" class=\"nav-link ");
      out.print( ("reminder".equals(request.getParameter("page"))) ? "active" : "" );
      out.write("\">\r\n");
      out.write("            <img src=\"assets/image/LogoNotif.png\" alt=\"Notification\" class=\"sidebar-icon\" id=\"notif-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"NoteServlet\" class=\"nav-link ");
      out.print( ("note".equals(request.getParameter("page"))) ? "active" : "" );
      out.write("\">\r\n");
      out.write("            <img src=\"assets/image/LogoNotes.png\" alt=\"Notes\" class=\"sidebar-icon\" id=\"notes-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"TaskServlet\" class=\"nav-link ");
      out.print( ("task".equals(request.getParameter("page"))) ? "active" : "" );
      out.write("\">\r\n");
      out.write("            <img src=\"assets/image/LogoToDoList.png\" alt=\"Tasks\" class=\"sidebar-icon\" id=\"task-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <!-- JournalEntry button added below Tasks -->\r\n");
      out.write("        <a href=\"JournalEntryServlet\" class=\"nav-link ");
      out.print( ("journal".equals(request.getParameter("page"))) ? "active" : "" );
      out.write("\">\r\n");
      out.write("            <img src=\"assets/image/LogoJournal.png\" alt=\"Journal\" class=\"sidebar-icon\" id=\"journal-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"HomeServlet?page=settings\" class=\"settings-link\">\r\n");
      out.write("            <img src=\"assets/image/LogoSetting.png\" alt=\"Settings\" class=\"sidebar-icon\" id=\"settings-icon\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <!-- Content Area -->\r\n");
      out.write("        <div class=\"content-area\">\r\n");
      out.write("            ");

            String content = (String) request.getAttribute("content");
            String pageParam = request.getParameter("page");
            
            // Antisipasi
            if (content == null && pageParam != null) {
                content = pageParam;
            }
            
      out.write("\r\n");
      out.write("            <div class=\"form-container\">\r\n");
      out.write("                ");

                if ("home".equals(content) || content == null){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "home.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("alarm".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "alarm.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("reminder".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "reminder.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("note".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "note.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("task".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "task.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("journal".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "journal.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("user".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "user_profile.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("settings".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "settings.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else if ("edit_profile".equals(content)){
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "edit_profile.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                } else {
                
      out.write("  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "home.jsp", out, true);
      out.write("\r\n");
      out.write("                ");

                }
                
      out.write("  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Universal Add Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"addModal\" tabindex=\"-1\">\r\n");
      out.write("        <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i> Add New Item\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- Activity Card -->\r\n");
      out.write("                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"add-card\">\r\n");
      out.write("                                <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fas fa-calendar-check\"></i> Add Activity\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <form action=\"AddTaskServlet\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"type\" value=\"activity\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"activityTitle\">Title</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"activityTitle\" name=\"title\" placeholder=\"Activity title\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"activityDescription\">Description</label>\r\n");
      out.write("                                        <textarea class=\"form-control\" id=\"activityDescription\" name=\"description\" placeholder=\"Activity description\"></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"activityStartTime\">Start Time</label>\r\n");
      out.write("                                        <input type=\"datetime-local\" class=\"form-control\" id=\"activityStartTime\" name=\"startTime\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"activityEndTime\">End Time (Optional)</label>\r\n");
      out.write("                                        <input type=\"datetime-local\" class=\"form-control\" id=\"activityEndTime\" name=\"endTime\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary w-100\">Add Activity</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- To-Do Item Card -->\r\n");
      out.write("                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"add-card\">\r\n");
      out.write("                                <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fas fa-tasks\"></i> Add To-Do Item\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <form action=\"AddTaskServlet\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"type\" value=\"todoitem\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"todoTitle\">Title</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"todoTitle\" name=\"title\" placeholder=\"Task title\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"todoTime\">Due Date & Time</label>\r\n");
      out.write("                                        <input type=\"datetime-local\" class=\"form-control\" id=\"todoTime\" name=\"dueDate\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"todoPriority\">Priority (1-10)</label>\r\n");
      out.write("                                        <input type=\"number\" class=\"form-control\" id=\"todoPriority\" name=\"priority\" min=\"1\" max=\"10\" placeholder=\"5\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary w-100\">Add To-Do Item</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Alarm Card -->\r\n");
      out.write("                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"add-card\">\r\n");
      out.write("                                <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-clock-rotate-left\"></i> Add Alarm\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <form action=\"AddAlarmServlet\" method=\"post\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"alarmTitle\">Title</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"alarmTitle\" name=\"title\" placeholder=\"e.g. Wake up\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"alarmTime\">Time</label>\r\n");
      out.write("                                        <input type=\"datetime-local\" class=\"form-control\" id=\"alarmTime\" name=\"time\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary w-100\">Add Alarm</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Reminder Card -->\r\n");
      out.write("                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"add-card\">\r\n");
      out.write("                                <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fas fa-bell\"></i> Add Reminder\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <form action=\"AddReminderServlet\" method=\"post\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"reminderTime\">Date & Time</label>\r\n");
      out.write("                                        <input type=\"datetime-local\" class=\"form-control\" id=\"reminderTime\" name=\"time\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"reminderMessage\">Message</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"reminderMessage\" name=\"message\" placeholder=\"Reminder message\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"reminderType\">Link to Task (Optional)</label>\r\n");
      out.write("                                        <select class=\"form-control\" id=\"reminderType\" name=\"type\">\r\n");
      out.write("                                            <option value=\"\">No task linked</option>\r\n");
      out.write("                                            <option value=\"todoitem\">To-Do Item</option>\r\n");
      out.write("                                            <option value=\"activity\">Activity</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary w-100\">Add Reminder</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Note Card -->\r\n");
      out.write("                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"add-card\">\r\n");
      out.write("                                <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fas fa-sticky-note\"></i> Add Note\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <form action=\"AddNoteServlet\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"noteType\" value=\"text\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"noteTitle\">Title</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"noteTitle\" name=\"title\" placeholder=\"Note title\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"noteContent\">Content</label>\r\n");
      out.write("                                        <textarea class=\"form-control\" id=\"noteContent\" name=\"textNote\" rows=\"4\" placeholder=\"Note content\" required></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary w-100\">Add Note</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Journal Card -->\r\n");
      out.write("                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                            <div class=\"add-card\">\r\n");
      out.write("                                <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fas fa-book\"></i> Add Journal Entry\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <form action=\"AddJournalEntryServlet\" method=\"post\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"journalTitle\">Title (Optional)</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"journalTitle\" name=\"title\" placeholder=\"Journal title\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"journalContent\">Content</label>\r\n");
      out.write("                                        <textarea class=\"form-control\" id=\"journalContent\" name=\"content\" rows=\"4\" placeholder=\"What's on your mind?\" required></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary w-100\">Add Journal Entry</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // Global variables for notification system\r\n");
      out.write("        let notificationData = {};\r\n");
      out.write("        let activeAlarms = [];\r\n");
      out.write("        let activeReminders = [];\r\n");
      out.write("        let checkInterval;\r\n");
      out.write("        \r\n");
      out.write("        // Initialize notification system\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // Get notification settings from hidden div\r\n");
      out.write("            const dataDiv = document.getElementById('notificationData');\r\n");
      out.write("            if (dataDiv) {\r\n");
      out.write("                notificationData = {\r\n");
      out.write("                    userId: dataDiv.dataset.userId,\r\n");
      out.write("                    alarmSound: dataDiv.dataset.alarmSound,\r\n");
      out.write("                    notificationSound: dataDiv.dataset.notificationSound\r\n");
      out.write("                };\r\n");
      out.write("                \r\n");
      out.write("                console.log('Notification system initialized:', notificationData);\r\n");
      out.write("                \r\n");
      out.write("                // Start checking for active alarms and reminders\r\n");
      out.write("                startNotificationCheck();\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Handle success/error messages\r\n");
      out.write("            handleUrlMessages();\r\n");
      out.write("            \r\n");
      out.write("            // Add animation classes to cards\r\n");
      out.write("            animateCards();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // Start periodic checking for notifications\r\n");
      out.write("        function startNotificationCheck() {\r\n");
      out.write("            // Check immediately\r\n");
      out.write("            checkForNotifications();\r\n");
      out.write("            \r\n");
      out.write("            // Then check every 30 seconds\r\n");
      out.write("            checkInterval = setInterval(checkForNotifications, 30000);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Check for active alarms and reminders\r\n");
      out.write("        function checkForNotifications() {\r\n");
      out.write("        const now = new Date();\r\n");
      out.write("\r\n");
      out.write("        // Mengambil jam dan menit lokal\r\n");
      out.write("        const currentTime = now.getHours().toString().padStart(2, '0') + ':' +\r\n");
      out.write("                            now.getMinutes().toString().padStart(2, '0');\r\n");
      out.write("\r\n");
      out.write("        // Mengambil tanggal lokal dengan metode Date yang lokal\r\n");
      out.write("        const year = now.getFullYear();\r\n");
      out.write("        const month = (now.getMonth() + 1).toString().padStart(2, '0');\r\n");
      out.write("        const day = now.getDate().toString().padStart(2, '0');\r\n");
      out.write("\r\n");
      out.write("        // Log nilai individual sebelum penggabungan\r\n");
      out.write("        console.log(\"Year:\", year);\r\n");
      out.write("        console.log(\"Month:\", month);\r\n");
      out.write("        console.log(\"Day:\", day);\r\n");
      out.write("\r\n");
      out.write("        const currentDate = year + \"-\" + month + \"-\" + day;\r\n");
      out.write("\r\n");
      out.write("        console.log('Checking notifications for:', currentDate, currentTime);\r\n");
      out.write("            \r\n");
      out.write("            // Check for alarms\r\n");
      out.write("            fetch('CheckActiveAlarmsServlet?userId=' + notificationData.userId + '&date=' + currentDate + '&time=' + currentTime)\r\n");
      out.write("                .then(response => response.json())\r\n");
      out.write("                .then(alarms => {\r\n");
      out.write("                    if (alarms && alarms.length > 0) {\r\n");
      out.write("                        alarms.forEach(alarm => {\r\n");
      out.write("                            if (!activeAlarms.includes(alarm.id)) {\r\n");
      out.write("                                showAlarmNotification(alarm);\r\n");
      out.write("                                activeAlarms.push(alarm.id);\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    console.log('CHECK:', alarms);\r\n");
      out.write("                    console.log('CHECK activeAlarms:', activeAlarms);\r\n");
      out.write("                    console.log('CheckActiveAlarmsServlet?userId=' + notificationData.userId + '&date=' + currentDate + '&time=' + currentTime);\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => console.error('Error checking alarms:', error));\r\n");
      out.write("            \r\n");
      out.write("            // Check for reminders\r\n");
      out.write("            fetch('CheckActiveRemindersServlet?userId=' + notificationData.userId + '&date=' + currentDate + '&time=' + currentTime)\r\n");
      out.write("                .then(response => response.json())\r\n");
      out.write("                .then(reminders => {\r\n");
      out.write("                    if (reminders && reminders.length > 0) {\r\n");
      out.write("                        reminders.forEach(reminder => {\r\n");
      out.write("                            if (!activeReminders.includes(reminder.id)) {\r\n");
      out.write("                                showReminderNotification(reminder);\r\n");
      out.write("                                activeReminders.push(reminder.id);\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    console.log('CHECK:', reminders);\r\n");
      out.write("                    console.log('CHECK activeReminders:', activeReminders);\r\n");
      out.write("                    console.log('CheckActiveRemindersServlet?userId=' + notificationData.userId + '&date=' + currentDate + '&time=' + currentTime);\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => console.error('Error checking reminders:', error));\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Show alarm notification with sound\r\n");
      out.write("        function showAlarmNotification(alarm) {\r\n");
      out.write("            console.log('Showing alarm notification:', alarm);\r\n");
      out.write("            \r\n");
      out.write("            // Play alarm sound\r\n");
      out.write("            playAlarmSound();\r\n");
      out.write("            \r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                title: '⏰ Alarm!',\r\n");
      out.write("                html: '<div class=\"text-center\">' +\r\n");
      out.write("                      '<i class=\"fas fa-alarm-clock fa-3x text-danger mb-3\"></i>' +\r\n");
      out.write("                      '<h4>' + alarm.title + '</h4>' +\r\n");
      out.write("                      '<p class=\"text-muted\">' + formatTime(alarm.time) + '</p>' +\r\n");
      out.write("                      '</div>',\r\n");
      out.write("                icon: 'warning',\r\n");
      out.write("                showCancelButton: true,\r\n");
      out.write("                confirmButtonText: 'Dismiss',\r\n");
      out.write("                cancelButtonText: 'Snooze (5 min)',\r\n");
      out.write("                confirmButtonColor: '#dc3545',\r\n");
      out.write("                cancelButtonColor: '#6c757d',\r\n");
      out.write("                allowOutsideClick: false,\r\n");
      out.write("                allowEscapeKey: false,\r\n");
      out.write("                customClass: {\r\n");
      out.write("                    popup: 'alarm-popup'\r\n");
      out.write("                }\r\n");
      out.write("            }).then((result) => {\r\n");
      out.write("                stopAlarmSound();\r\n");
      out.write("                if (result.isDismissed && result.dismiss === Swal.DismissReason.cancel) {\r\n");
      out.write("                    // Snooze for 5 minutes\r\n");
      out.write("                    snoozeAlarm(alarm.id, 5);\r\n");
      out.write("                } else {\r\n");
      out.write("                    // Mark as dismissed\r\n");
      out.write("                    dismissAlarm(alarm.id);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Show reminder notification with sound\r\n");
      out.write("        function showReminderNotification(reminder) {\r\n");
      out.write("            console.log('Showing reminder notification:', reminder);\r\n");
      out.write("            \r\n");
      out.write("            // Play notification sound\r\n");
      out.write("            playNotificationSound();\r\n");
      out.write("            \r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                title: '🔔 Reminder',\r\n");
      out.write("                html: '<div class=\"text-center\">' +\r\n");
      out.write("                      '<i class=\"fas fa-bell fa-3x text-primary mb-3\"></i>' +\r\n");
      out.write("                      '<h4>' + reminder.message + '</h4>' +\r\n");
      out.write("                      '<p class=\"text-muted\">' + formatTime(reminder.time) + '</p>' +\r\n");
      out.write("                      (reminder.type ? '<small class=\"badge bg-secondary\">' + reminder.type + '</small>' : '') +\r\n");
      out.write("                      '</div>',\r\n");
      out.write("                icon: 'info',\r\n");
      out.write("                confirmButtonText: 'Got it!',\r\n");
      out.write("                confirmButtonColor: '#0d6efd',\r\n");
      out.write("                timer: 10000,\r\n");
      out.write("                timerProgressBar: true,\r\n");
      out.write("                customClass: {\r\n");
      out.write("                    popup: 'reminder-popup'\r\n");
      out.write("                }\r\n");
      out.write("            }).then(() => {\r\n");
      out.write("                stopNotificationSound();\r\n");
      out.write("                markReminderAsShown(reminder.id);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Play alarm sound\r\n");
      out.write("        function playAlarmSound() {\r\n");
      out.write("            const audio = document.getElementById('alarmAudio');\r\n");
      out.write("            audio.src = 'assets/sound/alarm/' + notificationData.alarmSound + '.mp3';\r\n");
      out.write("            audio.loop = true;\r\n");
      out.write("            audio.play().catch(e => console.error('Error playing alarm sound:', e));\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Play notification sound\r\n");
      out.write("        function playNotificationSound() {\r\n");
      out.write("            const audio = document.getElementById('notificationAudio');\r\n");
      out.write("            audio.src = 'assets/sound/notif/' + notificationData.notificationSound + '.mp3';\r\n");
      out.write("            audio.loop = false;\r\n");
      out.write("            audio.play().catch(e => console.error('Error playing notification sound:', e));\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Stop alarm sound\r\n");
      out.write("        function stopAlarmSound() {\r\n");
      out.write("            const audio = document.getElementById('alarmAudio');\r\n");
      out.write("            audio.pause();\r\n");
      out.write("            audio.currentTime = 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Stop notification sound\r\n");
      out.write("        function stopNotificationSound() {\r\n");
      out.write("            const audio = document.getElementById('notificationAudio');\r\n");
      out.write("            audio.pause();\r\n");
      out.write("            audio.currentTime = 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Snooze alarm\r\n");
      out.write("        function snoozeAlarm(alarmId, minutes) {\r\n");
      out.write("            fetch('SnoozeAlarmServlet', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("                },\r\n");
      out.write("                body: 'alarmId=' + alarmId + '&minutes=' + minutes\r\n");
      out.write("            }).then(() => {\r\n");
      out.write("                // Remove from active alarms so it can trigger again\r\n");
      out.write("                activeAlarms = activeAlarms.filter(id => id !== alarmId);\r\n");
      out.write("                \r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'success',\r\n");
      out.write("                    title: 'Alarm Snoozed',\r\n");
      out.write("                    text: 'Alarm will ring again in ' + minutes + ' minutes',\r\n");
      out.write("                    timer: 2000,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Dismiss alarm\r\n");
      out.write("        function dismissAlarm(alarmId) {\r\n");
      out.write("            fetch('DismissAlarmServlet', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("                },\r\n");
      out.write("                body: 'alarmId=' + alarmId\r\n");
      out.write("            }).then(() => {\r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'success',\r\n");
      out.write("                    title: 'Alarm Dismissed',\r\n");
      out.write("                    text: 'The alarm has been successfully dismissed.',\r\n");
      out.write("                    timer: 2000,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Mark reminder as shown\r\n");
      out.write("        function markReminderAsShown(reminderId) {\r\n");
      out.write("            fetch('MarkReminderShownServlet', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("                },\r\n");
      out.write("                body: 'reminderId=' + reminderId\r\n");
      out.write("            }).then(() => {\r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'success',\r\n");
      out.write("                    title: 'Reminder Marked',\r\n");
      out.write("                    text: 'The reminder has been marked as shown.',\r\n");
      out.write("                    timer: 2000,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Format time for display\r\n");
      out.write("        function formatTime(timeString) {\r\n");
      out.write("            const date = new Date(timeString);\r\n");
      out.write("            return date.toLocaleTimeString('en-US', {\r\n");
      out.write("                hour: '2-digit',\r\n");
      out.write("                minute: '2-digit',\r\n");
      out.write("                hour12: true\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Sidebar icon hover effects\r\n");
      out.write("        // document.getElementById(\"add-icon\").onmouseover = function() {\r\n");
      out.write("        //     this.src = \"assets/image/LogoAddHover.png\";\r\n");
      out.write("        // };\r\n");
      out.write("        // document.getElementById(\"add-icon\").onmouseout = function() {\r\n");
      out.write("        //     this.src = \"assets/image/LogoAdd.png\";\r\n");
      out.write("        // };\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"home-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/HomeHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"home-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoHome.png\";\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"alarm-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/AlarmHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"alarm-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoAlarm.png\";\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"notif-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/NotifHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"notif-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoNotif.png\";\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"notes-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/NotesHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"notes-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoNotes.png\";\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"task-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/ToDoListHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"task-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoToDoList.png\";\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"journal-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/JournalHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"journal-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoJournal.png\";\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"settings-icon\").onmouseover = function() {\r\n");
      out.write("            this.src = \"assets/image/SettingHover.png\";\r\n");
      out.write("        };\r\n");
      out.write("        document.getElementById(\"settings-icon\").onmouseout = function() {\r\n");
      out.write("            this.src = \"assets/image/LogoSetting.png\";\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Show add modal\r\n");
      out.write("        // function showAddModal() {\r\n");
      out.write("        //     // Set default times\r\n");
      out.write("        //     const now = new Date();\r\n");
      out.write("        //     now.setMinutes(now.getMinutes() - now.getTimezoneOffset());\r\n");
      out.write("        //     const defaultTime = now.toISOString().slice(0, 16);\r\n");
      out.write("            \r\n");
      out.write("        //     document.getElementById('activityStartTime').value = defaultTime;\r\n");
      out.write("        //     document.getElementById('todoTime').value = defaultTime;\r\n");
      out.write("        //     document.getElementById('alarmTime').value = defaultTime;\r\n");
      out.write("        //     document.getElementById('reminderTime').value = defaultTime;\r\n");
      out.write("            \r\n");
      out.write("        //     var addModal = new bootstrap.Modal(document.getElementById('addModal'));\r\n");
      out.write("        //     addModal.show();\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("        // Handle success/error messages with SweetAlert2\r\n");
      out.write("        function handleUrlMessages() {\r\n");
      out.write("            const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("            const success = urlParams.get('success');\r\n");
      out.write("            const error = urlParams.get('error');\r\n");
      out.write("\r\n");
      out.write("            if (success) {\r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'success',\r\n");
      out.write("                    title: 'Success!',\r\n");
      out.write("                    text: success,\r\n");
      out.write("                    timer: 3000,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (error) {\r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'error',\r\n");
      out.write("                    title: 'Error!',\r\n");
      out.write("                    text: error,\r\n");
      out.write("                    timer: 3000,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Add animation classes to cards on load\r\n");
      out.write("        function animateCards() {\r\n");
      out.write("            const cards = document.querySelectorAll('.dashboard-card, .add-card');\r\n");
      out.write("            cards.forEach((card, index) => {\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    card.classList.add('fade-in');\r\n");
      out.write("                }, index * 100);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Cleanup when page unloads\r\n");
      out.write("        window.addEventListener('beforeunload', function() {\r\n");
      out.write("            if (checkInterval) {\r\n");
      out.write("                clearInterval(checkInterval);\r\n");
      out.write("            }\r\n");
      out.write("            stopAlarmSound();\r\n");
      out.write("            stopNotificationSound();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        .alarm-popup {\r\n");
      out.write("            animation: shake 0.5s ease-in-out infinite alternate;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes shake {\r\n");
      out.write("            0% { transform: translateX(0); }\r\n");
      out.write("            100% { transform: translateX(5px); }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .reminder-popup {\r\n");
      out.write("            animation: fadeInBounce 0.5s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes fadeInBounce {\r\n");
      out.write("            0% { opacity: 0; transform: scale(0.3); }\r\n");
      out.write("            50% { opacity: 1; transform: scale(1.05); }\r\n");
      out.write("            100% { opacity: 1; transform: scale(1); }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
