/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-14 06:57:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.JournalEntry;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Calendar;

public final class journal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.JournalEntry");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-book-open\"></i>\r\n");
      out.write("            My Journal\r\n");
      out.write("        </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "User" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

@SuppressWarnings("unchecked")
List<JournalEntry> journalList = (List<JournalEntry>) request.getAttribute("journalList");

if (journalList != null && !journalList.isEmpty()) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy");
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    SimpleDateFormat fullFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm");
    
    // Get today and yesterday dates for comparison
    Calendar today = Calendar.getInstance();
    today.set(Calendar.HOUR_OF_DAY, 0);
    today.set(Calendar.MINUTE, 0);
    today.set(Calendar.SECOND, 0);
    today.set(Calendar.MILLISECOND, 0);
    
    Calendar yesterday = (Calendar) today.clone();
    yesterday.add(Calendar.DAY_OF_MONTH, -1);
    
    // Counters for each section
    int todayCount = 0;
    int yesterdayCount = 0;
    int earlierCount = 0;
    
    // First pass: count entries for each section
    for (JournalEntry entry : journalList) {
        if (entry == null || entry.getEntrydate() == null) continue;
        
        Calendar entryDate = Calendar.getInstance();
        entryDate.setTime(entry.getEntrydate());
        entryDate.set(Calendar.HOUR_OF_DAY, 0);
        entryDate.set(Calendar.MINUTE, 0);
        entryDate.set(Calendar.SECOND, 0);
        entryDate.set(Calendar.MILLISECOND, 0);
        
        if (entryDate.equals(today)) {
            todayCount++;
        } else if (entryDate.equals(yesterday)) {
            yesterdayCount++;
        } else {
            earlierCount++;
        }
    }
    
    // Display today's entries
    if (todayCount > 0) {

      out.write("\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-sun section-icon\" style=\"color: #f39c12;\"></i>\r\n");
      out.write("            Today's Entries\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"journal-grid\">\r\n");

        for (JournalEntry entry : journalList) {
            if (entry == null || entry.getEntrydate() == null) continue;
            
            Calendar entryDate = Calendar.getInstance();
            entryDate.setTime(entry.getEntrydate());
            entryDate.set(Calendar.HOUR_OF_DAY, 0);
            entryDate.set(Calendar.MINUTE, 0);
            entryDate.set(Calendar.SECOND, 0);
            entryDate.set(Calendar.MILLISECOND, 0);
            
            if (entryDate.equals(today)) {
                // Safely escape content for JavaScript
                String safeTitle = "";
                String safeContent = "";
                if (entry.getTitle() != null) {
                    safeTitle = entry.getTitle()
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "");
                }
                if (entry.getContent() != null) {
                    safeContent = entry.getContent()
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "");
                }

      out.write("\r\n");
      out.write("                <div class=\"journal-card\">\r\n");
      out.write("                    <div class=\"journal-actions\">\r\n");
      out.write("                        <button class=\"action-btn edit-btn\" onclick=\"editJournal(");
      out.print( entry.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( safeTitle );
      out.write("', '");
      out.print( safeContent );
      out.write("', '");
      out.print( fullFormat.format(entry.getEntrydate()) );
      out.write("')\">\r\n");
      out.write("                            <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"action-btn delete-btn\" onclick=\"deleteJournal(");
      out.print( entry.getId() );
      out.write(")\">\r\n");
      out.write("                            <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"journal-card-title\">\r\n");
      out.write("                        <i class=\"fas fa-feather-alt\"></i> ");
      out.print( entry.getTitle() != null ? entry.getTitle() : "Journal Entry" );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"journal-content\">");
      out.print( entry.getContent() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"journal-meta\">\r\n");
      out.write("                        <span class=\"journal-date\">\r\n");
      out.write("                            <i class=\"fas fa-clock\"></i> Today, ");
      out.print( timeFormat.format(entry.getEntrydate()) );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");

            }
        }

      out.write("\r\n");
      out.write("        </div>\r\n");

    }
    
    // Display yesterday's entries
    if (yesterdayCount > 0) {

      out.write("\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-moon section-icon\" style=\"color: #9b59b6;\"></i>\r\n");
      out.write("            Yesterday's Entries\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"journal-grid\">\r\n");

        for (JournalEntry entry : journalList) {
            if (entry == null || entry.getEntrydate() == null) continue;
            
            Calendar entryDate = Calendar.getInstance();
            entryDate.setTime(entry.getEntrydate());
            entryDate.set(Calendar.HOUR_OF_DAY, 0);
            entryDate.set(Calendar.MINUTE, 0);
            entryDate.set(Calendar.SECOND, 0);
            entryDate.set(Calendar.MILLISECOND, 0);
            
            if (entryDate.equals(yesterday)) {
                // Safely escape content for JavaScript
                String safeTitle = "";
                String safeContent = "";
                if (entry.getTitle() != null) {
                    safeTitle = entry.getTitle()
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "");
                }
                if (entry.getContent() != null) {
                    safeContent = entry.getContent()
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "");
                }

      out.write("\r\n");
      out.write("                <div class=\"journal-card\">\r\n");
      out.write("                    <div class=\"journal-actions\">\r\n");
      out.write("                        <button class=\"action-btn edit-btn\" onclick=\"editJournal(");
      out.print( entry.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( safeTitle );
      out.write("', '");
      out.print( safeContent );
      out.write("', '");
      out.print( fullFormat.format(entry.getEntrydate()) );
      out.write("')\">\r\n");
      out.write("                            <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"action-btn delete-btn\" onclick=\"deleteJournal(");
      out.print( entry.getId() );
      out.write(")\">\r\n");
      out.write("                            <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"journal-card-title\">\r\n");
      out.write("                        <i class=\"fas fa-feather-alt\"></i> ");
      out.print( entry.getTitle() != null ? entry.getTitle() : "Journal Entry" );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"journal-content\">");
      out.print( entry.getContent() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"journal-meta\">\r\n");
      out.write("                        <span class=\"journal-date\">\r\n");
      out.write("                            <i class=\"fas fa-clock\"></i> Yesterday, ");
      out.print( timeFormat.format(entry.getEntrydate()) );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");

            }
        }

      out.write("\r\n");
      out.write("        </div>\r\n");

    }
    
    // Display earlier entries
    if (earlierCount > 0) {

      out.write("\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-history section-icon\" style=\"color: #95a5a6;\"></i>\r\n");
      out.write("            Earlier Entries\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"journal-grid\">\r\n");

        for (JournalEntry entry : journalList) {
            if (entry == null || entry.getEntrydate() == null) continue;
            
            Calendar entryDate = Calendar.getInstance();
            entryDate.setTime(entry.getEntrydate());
            entryDate.set(Calendar.HOUR_OF_DAY, 0);
            entryDate.set(Calendar.MINUTE, 0);
            entryDate.set(Calendar.SECOND, 0);
            entryDate.set(Calendar.MILLISECOND, 0);
            
            if (!entryDate.equals(today) && !entryDate.equals(yesterday)) {
                // Safely escape content for JavaScript
                String safeTitle = "";
                String safeContent = "";
                if (entry.getTitle() != null) {
                    safeTitle = entry.getTitle()
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "");
                }
                if (entry.getContent() != null) {
                    safeContent = entry.getContent()
                        .replace("\\", "\\\\")
                        .replace("'", "\\'")
                        .replace("\n", "\\n")
                        .replace("\r", "");
                }

      out.write("\r\n");
      out.write("                <div class=\"journal-card\">\r\n");
      out.write("                    <div class=\"journal-actions\">\r\n");
      out.write("                        <button class=\"action-btn edit-btn\" onclick=\"editJournal(");
      out.print( entry.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( safeTitle );
      out.write("', '");
      out.print( safeContent );
      out.write("', '");
      out.print( fullFormat.format(entry.getEntrydate()) );
      out.write("')\">\r\n");
      out.write("                            <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"action-btn delete-btn\" onclick=\"deleteJournal(");
      out.print( entry.getId() );
      out.write(")\">\r\n");
      out.write("                            <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"journal-card-title\">\r\n");
      out.write("                        <i class=\"fas fa-feather-alt\"></i> ");
      out.print( entry.getTitle() != null ? entry.getTitle() : "Journal Entry" );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"journal-content\">");
      out.print( entry.getContent() );
      out.write("</div>\r\n");
      out.write("                    <div class=\"journal-meta\">\r\n");
      out.write("                        <span class=\"journal-date\">\r\n");
      out.write("                            <i class=\"fas fa-calendar\"></i> ");
      out.print( dateFormat.format(entry.getEntrydate()) );
      out.write(" at ");
      out.print( timeFormat.format(entry.getEntrydate()) );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");

            }
        }

      out.write("\r\n");
      out.write("        </div>\r\n");

    }
} else {

      out.write("\r\n");
      out.write("    <div class=\"empty-state\">\r\n");
      out.write("        <i class=\"fas fa-book-open fa-4x\"></i>\r\n");
      out.write("        <h3>No journal entries yet</h3>\r\n");
      out.write("        <p>Start documenting your thoughts and experiences!</p>\r\n");
      out.write("        <button class=\"btn btn-primary btn-lg\" onclick=\"showAddJournalModal()\">\r\n");
      out.write("            <i class=\"fas fa-plus\"></i> Write Your First Entry\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Floating Add Button -->\r\n");
      out.write("<button class=\"floating-add-btn\" onclick=\"showAddJournalModal()\">\r\n");
      out.write("    <i class=\"fas fa-plus\"></i>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Journal Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addJournalModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-feather-alt\"></i> New Journal Entry\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"AddJournalEntryServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"addJournalTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"addJournalTitle\" name=\"title\" \r\n");
      out.write("                               placeholder=\"Give your entry a title...\" maxlength=\"100\">\r\n");
      out.write("                        <div class=\"form-text\">Optional - leave blank for default title</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"addJournalContent\" class=\"form-label\">What's on your mind?</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"addJournalContent\" name=\"content\" rows=\"10\" \r\n");
      out.write("                                  placeholder=\"Write your thoughts, experiences, or reflections here...\" required></textarea>\r\n");
      out.write("                        <div class=\"form-text\">Express yourself freely - this is your personal space.</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i> Cancel\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save\"></i> Save Entry\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Journal Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editJournalModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-edit\"></i> Edit Journal Entry\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditJournalEntryServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"editJournalId\" name=\"id\">\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"editJournalTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editJournalTitle\" name=\"title\" \r\n");
      out.write("                               placeholder=\"Give your entry a title...\" maxlength=\"100\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"editJournalDate\" class=\"form-label\">Date & Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"editJournalDate\" name=\"entrydate\" readonly>\r\n");
      out.write("                        <div class=\"form-text\">Entry date cannot be changed</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"editJournalContent\" class=\"form-label\">Content</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"editJournalContent\" name=\"content\" rows=\"10\" required></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i> Cancel\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save\"></i> Save Changes\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Include SweetAlert2 -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Show add modal\r\n");
      out.write("    function showAddJournalModal() {\r\n");
      out.write("        // Reset form\r\n");
      out.write("        document.getElementById('addJournalTitle').value = '';\r\n");
      out.write("        document.getElementById('addJournalContent').value = '';\r\n");
      out.write("        \r\n");
      out.write("        var addModal = new bootstrap.Modal(document.getElementById('addJournalModal'));\r\n");
      out.write("        addModal.show();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Edit journal entry\r\n");
      out.write("    function editJournal(id, title, content, entrydate) {\r\n");
      out.write("        document.getElementById('editJournalId').value = id;\r\n");
      out.write("        document.getElementById('editJournalTitle').value = title;\r\n");
      out.write("        document.getElementById('editJournalContent').value = content.replace(/\\\\n/g, '\\n');\r\n");
      out.write("        document.getElementById('editJournalDate').value = entrydate;\r\n");
      out.write("        \r\n");
      out.write("        var editModal = new bootstrap.Modal(document.getElementById('editJournalModal'));\r\n");
      out.write("        editModal.show();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Delete journal entry with SweetAlert2\r\n");
      out.write("    function deleteJournal(id) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            title: 'Are you sure?',\r\n");
      out.write("            text: \"You won't be able to revert this journal entry!\",\r\n");
      out.write("            icon: 'warning',\r\n");
      out.write("            showCancelButton: true,\r\n");
      out.write("            confirmButtonColor: '#dc3545',\r\n");
      out.write("            cancelButtonColor: '#6c757d',\r\n");
      out.write("            confirmButtonText: 'Yes, delete it!',\r\n");
      out.write("            cancelButtonText: 'Cancel'\r\n");
      out.write("        }).then((result) => {\r\n");
      out.write("            if (result.isConfirmed) {\r\n");
      out.write("                window.location.href = 'DeleteJournalEntryServlet?id=' + id;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Auto-resize textarea\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const textareas = document.querySelectorAll('textarea');\r\n");
      out.write("        textareas.forEach(textarea => {\r\n");
      out.write("            textarea.addEventListener('input', function() {\r\n");
      out.write("                this.style.height = 'auto';\r\n");
      out.write("                this.style.height = this.scrollHeight + 'px';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
