/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-13 07:42:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.TextNote;
import model.VoiceNote;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;

public final class note_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.VoiceNote");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("model.TextNote");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-sticky-note\"></i>\r\n");
      out.write("            Notes\r\n");
      out.write("        </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "User" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

@SuppressWarnings("unchecked")
List<TextNote> textNotes = (List<TextNote>) request.getAttribute("textNotes");
@SuppressWarnings("unchecked")
List<VoiceNote> voiceNotes = (List<VoiceNote>) request.getAttribute("voiceNotes");

SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy HH:mm");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Notes Container with Two Columns -->\r\n");
      out.write("<div class=\"notes-container\">\r\n");
      out.write("    <!-- Text Notes Column -->\r\n");
      out.write("    <div class=\"notes-column\">\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-file-alt section-icon\"></i>\r\n");
      out.write("            Text Notes\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if (textNotes != null && !textNotes.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"notes-grid\">\r\n");
      out.write("                ");
 for (TextNote note : textNotes) { 
                    if (note != null && note.getTitle() != null) {
                        // Safely escape content for JavaScript
                        String safeTitle = note.getTitle().replace("\\", "\\\\").replace("'", "\\'");
                        String safeContent = "";
                        if (note.getTextNote() != null) {
                            safeContent = note.getTextNote()
                                .replace("\\", "\\\\")
                                .replace("'", "\\'")
                                .replace("\n", "\\n")
                                .replace("\r", "");
                        }
                
      out.write("\r\n");
      out.write("                    <div class=\"note-card\">\r\n");
      out.write("                        <div class=\"note-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editTextNote(");
      out.print( note.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( safeTitle );
      out.write("', '");
      out.print( safeContent );
      out.write("')\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteNote(");
      out.print( note.getId() );
      out.write(", 'text')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"note-title\">");
      out.print( note.getTitle() );
      out.write("</div>\r\n");
      out.write("                        ");
 if (note.getTextNote() != null && !note.getTextNote().trim().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"note-content\">");
      out.print( note.getTextNote() );
      out.write("</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"note-meta\">\r\n");
      out.write("                            <div class=\"note-date\">\r\n");
      out.write("                                <i class=\"fas fa-calendar-alt\"></i>\r\n");
      out.write("                                ");
 if (note.getCreatedDate() != null) { 
      out.write("\r\n");
      out.write("                                    ");
      out.print( dateFormat.format(note.getCreatedDate()) );
      out.write("\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    No date\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <i class=\"fas fa-file-alt fa-3x\"></i>\r\n");
      out.write("                <h3>No Text Notes Yet</h3>\r\n");
      out.write("                <p>Create your first text note to get started</p>\r\n");
      out.write("                <button class=\"btn btn-primary mt-3\" onclick=\"showAddModalNote('text')\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add Text Note\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Voice Notes Column -->\r\n");
      out.write("    <div class=\"notes-column\">\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-microphone section-icon\"></i>\r\n");
      out.write("            Voice Notes\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if (voiceNotes != null && !voiceNotes.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"notes-grid\">\r\n");
      out.write("                ");
 for (VoiceNote note : voiceNotes) { 
                    if (note != null && note.getTitle() != null) {
                        // Safely escape content for JavaScript
                        String safeTitle = note.getTitle().replace("\\", "\\\\").replace("'", "\\'");
                        String safeVoiceUrl = "";
                        if (note.getVoiceNote() != null) {
                            safeVoiceUrl = note.getVoiceNote().replace("'", "\\'");
                        }
                
      out.write("\r\n");
      out.write("                    <div class=\"note-card\">\r\n");
      out.write("                        <div class=\"note-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editVoiceNote(");
      out.print( note.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( safeTitle );
      out.write("', '");
      out.print( safeVoiceUrl );
      out.write("')\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteNote(");
      out.print( note.getId() );
      out.write(", 'voice')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"note-title\">");
      out.print( note.getTitle() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"note-content\">\r\n");
      out.write("                            ");
 if (note.getVoiceNote() != null && !note.getVoiceNote().isEmpty()) { 
      out.write("\r\n");
      out.write("                                <audio controls class=\"audio-player\">\r\n");
      out.write("                                    <source src=\"");
      out.print( note.getVoiceNote() );
      out.write("\" type=\"audio/mpeg\">\r\n");
      out.write("                                    <source src=\"");
      out.print( note.getVoiceNote() );
      out.write("\" type=\"audio/wav\">\r\n");
      out.write("                                    <source src=\"");
      out.print( note.getVoiceNote() );
      out.write("\" type=\"audio/ogg\">\r\n");
      out.write("                                    Your browser does not support the audio element.\r\n");
      out.write("                                </audio>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <p class=\"text-muted\">No audio recording available</p>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"note-meta\">\r\n");
      out.write("                            <div class=\"note-date\">\r\n");
      out.write("                                <i class=\"fas fa-calendar-alt\"></i>\r\n");
      out.write("                                ");
 if (note.getCreatedDate() != null) { 
      out.write("\r\n");
      out.write("                                    ");
      out.print( dateFormat.format(note.getCreatedDate()) );
      out.write("\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    No date\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <i class=\"fas fa-microphone fa-3x\"></i>\r\n");
      out.write("                <h3>No Voice Notes Yet</h3>\r\n");
      out.write("                <p>Record your first voice note to get started</p>\r\n");
      out.write("                <button class=\"btn btn-primary mt-3\" onclick=\"showAddModalNote('voice')\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add Voice Note\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<button class=\"floating-add-btn\" onclick=\"showAddModalNote()\">\r\n");
      out.write("    <i class=\"fas fa-plus\"></i>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Note Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"modaladd\" tabindex=\"-1\" aria-labelledby=\"modaladdLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"modaladdLabel\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add New Note\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <ul class=\"nav nav-tabs\" id=\"noteTypeTabs\" role=\"tablist\">\r\n");
      out.write("                    <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                        <button class=\"nav-link active\" id=\"text-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#text-note\" type=\"button\" role=\"tab\">\r\n");
      out.write("                            <i class=\"fas fa-file-alt me-2\"></i>Text Note\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                        <button class=\"nav-link\" id=\"voice-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#voice-note\" type=\"button\" role=\"tab\">\r\n");
      out.write("                            <i class=\"fas fa-microphone me-2\"></i>Voice Note\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"tab-content mt-3\" id=\"noteTypeContent\">\r\n");
      out.write("                    <!-- Text Note Form -->\r\n");
      out.write("                    <div class=\"tab-pane fade show active\" id=\"text-note\" role=\"tabpanel\">\r\n");
      out.write("                        <form action=\"AddNoteServlet\" method=\"post\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"noteType\" value=\"text\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"textNoteTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"textNoteTitle\" name=\"title\" placeholder=\"Enter note title\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"textNoteContent\" class=\"form-label\">Content</label>\r\n");
      out.write("                                <textarea class=\"form-control\" id=\"textNoteContent\" name=\"textNote\" rows=\"8\" placeholder=\"Enter your note content here...\" required></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"text-end\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                                    <i class=\"fas fa-save me-2\"></i>Save Text Note\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Voice Note Form -->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"voice-note\" role=\"tabpanel\">\r\n");
      out.write("                        <form action=\"AddNoteServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"noteType\" value=\"voice\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"voiceNoteTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"voiceNoteTitle\" name=\"title\" placeholder=\"Enter voice note title\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Recording Section -->\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Record Audio</label>\r\n");
      out.write("                                <div class=\"recording-controls text-center mb-3\">\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-danger me-2\" id=\"recordButton\">\r\n");
      out.write("                                        <i class=\"fas fa-microphone\"></i> Record\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-secondary me-2\" id=\"stopButton\" disabled>\r\n");
      out.write("                                        <i class=\"fas fa-stop\"></i> Stop\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-primary\" id=\"playButton\" disabled>\r\n");
      out.write("                                        <i class=\"fas fa-play\"></i> Play\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"recordingStatus\" class=\"text-center mb-2\"></div>\r\n");
      out.write("                                <audio id=\"recordedAudio\" controls style=\"width: 100%; display: none;\"></audio>\r\n");
      out.write("                                <input type=\"hidden\" id=\"recordedAudioData\" name=\"voicerecord\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- File Upload Section -->\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"voiceNoteFile\" class=\"form-label\">Or Upload Audio File</label>\r\n");
      out.write("                                <input type=\"file\" class=\"form-control\" id=\"voiceNoteFile\" name=\"voiceNote\" accept=\"audio/*\">\r\n");
      out.write("                                <small class=\"form-text text-muted\">Supported formats: MP3, WAV, OGG</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- URL Section -->\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"voiceNoteUrl\" class=\"form-label\">Or Enter Audio URL</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"voiceNoteUrl\" name=\"voiceUrl\" placeholder=\"https://example.com/audio.mp3\">\r\n");
      out.write("                                <small class=\"form-text text-muted\">Leave empty if recording or uploading a file</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"text-end\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                                    <i class=\"fas fa-save me-2\"></i>Save Voice Note\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Text Note Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editTextNoteModal\" tabindex=\"-1\" aria-labelledby=\"editTextNoteModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"editTextNoteModalLabel\">\r\n");
      out.write("                    <i class=\"fas fa-edit\"></i> Edit Text Note\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditNoteServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" id=\"editTextNoteId\" name=\"id\">\r\n");
      out.write("                <input type=\"hidden\" name=\"noteType\" value=\"text\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"editTextNoteTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editTextNoteTitle\" name=\"title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"editTextNoteContent\" class=\"form-label\">Content</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"editTextNoteContent\" name=\"textNote\" rows=\"8\" required></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save me-2\"></i>Update Note\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Voice Note Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editVoiceNoteModal\" tabindex=\"-1\" aria-labelledby=\"editVoiceNoteModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"editVoiceNoteModalLabel\">\r\n");
      out.write("                    <i class=\"fas fa-edit\"></i> Edit Voice Note\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditNoteServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <input type=\"hidden\" id=\"editVoiceNoteId\" name=\"id\">\r\n");
      out.write("                <input type=\"hidden\" name=\"noteType\" value=\"voice\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"editVoiceNoteTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editVoiceNoteTitle\" name=\"title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Current Voice File Info -->\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label\">Current Audio</label>\r\n");
      out.write("                        <div class=\"current-file-info p-3 bg-light rounded\">\r\n");
      out.write("                            <audio controls class=\"audio-player mb-2\" id=\"currentVoicePlayer\" style=\"width: 100%;\">\r\n");
      out.write("                                <source id=\"currentVoiceSource\" src=\"assets/image/placeholder.svg\" type=\"audio/mpeg\">\r\n");
      out.write("                                Your browser does not support the audio element.\r\n");
      out.write("                            </audio>\r\n");
      out.write("                            <small class=\"text-muted\">Current file: <span id=\"currentFileName\">No file</span></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Upload New Voice File -->\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"editVoiceFile\" class=\"form-label\">Upload New Audio File (Optional)</label>\r\n");
      out.write("                        <input type=\"file\" class=\"form-control\" id=\"editVoiceFile\" name=\"voiceNote\" accept=\"audio/*\">\r\n");
      out.write("                        <small class=\"form-text text-muted\">Leave empty to keep current audio</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Alternative: Voice URL -->\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"editVoiceUrl\" class=\"form-label\">Or Enter New Audio URL</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editVoiceUrl\" name=\"voiceUrl\" placeholder=\"https://example.com/audio.mp3\">\r\n");
      out.write("                        <small class=\"form-text text-muted\">Leave empty if uploading a file above</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save me-2\"></i>Update Voice Note\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Include SweetAlert2 -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let mediaRecorder;\r\n");
      out.write("    let audioChunks = [];\r\n");
      out.write("    let audioBlob;\r\n");
      out.write("    let audioUrl;\r\n");
      out.write("    \r\n");
      out.write("    function showAddModalNote(type = null) {\r\n");
      out.write("        const modal = new bootstrap.Modal(document.getElementById('modaladd'));\r\n");
      out.write("        modal.show();\r\n");
      out.write("        \r\n");
      out.write("        // Reset forms\r\n");
      out.write("        document.getElementById('textNoteTitle').value = '';\r\n");
      out.write("        document.getElementById('textNoteContent').value = '';\r\n");
      out.write("        document.getElementById('voiceNoteTitle').value = '';\r\n");
      out.write("        document.getElementById('voiceNoteFile').value = '';\r\n");
      out.write("        document.getElementById('voiceNoteUrl').value = '';\r\n");
      out.write("        document.getElementById('recordedAudioData').value = '';\r\n");
      out.write("        \r\n");
      out.write("        // Reset recording UI\r\n");
      out.write("        resetRecordingUI();\r\n");
      out.write("        \r\n");
      out.write("        // Switch to specific tab if type is specified\r\n");
      out.write("        if (type === 'text') {\r\n");
      out.write("            document.getElementById('text-tab').click();\r\n");
      out.write("        } else if (type === 'voice') {\r\n");
      out.write("            document.getElementById('voice-tab').click();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function editTextNote(id, title, content) {\r\n");
      out.write("        try {\r\n");
      out.write("            document.getElementById('editTextNoteId').value = id;\r\n");
      out.write("            document.getElementById('editTextNoteTitle').value = title || '';\r\n");
      out.write("            document.getElementById('editTextNoteContent').value = content.replace(/\\\\n/g, '\\n') || '';\r\n");
      out.write("            \r\n");
      out.write("            const modal = new bootstrap.Modal(document.getElementById('editTextNoteModal'));\r\n");
      out.write("            modal.show();\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error('Error opening text note edit modal:', error);\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                icon: 'error',\r\n");
      out.write("                title: 'Error',\r\n");
      out.write("                text: 'Error opening edit form. Please try again.'\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function editVoiceNote(id, title, voiceUrl) {\r\n");
      out.write("        try {\r\n");
      out.write("            document.getElementById('editVoiceNoteId').value = id;\r\n");
      out.write("            document.getElementById('editVoiceNoteTitle').value = title || '';\r\n");
      out.write("            \r\n");
      out.write("            // Set current voice file info\r\n");
      out.write("            if (voiceUrl) {\r\n");
      out.write("                document.getElementById('currentVoiceSource').src = voiceUrl;\r\n");
      out.write("                document.getElementById('currentVoicePlayer').load();\r\n");
      out.write("                document.getElementById('currentFileName').textContent = voiceUrl.split('/').pop();\r\n");
      out.write("                document.getElementById('editVoiceUrl').value = voiceUrl;\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById('currentFileName').textContent = 'No file';\r\n");
      out.write("                document.getElementById('editVoiceUrl').value = '';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            const modal = new bootstrap.Modal(document.getElementById('editVoiceNoteModal'));\r\n");
      out.write("            modal.show();\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error('Error opening voice note edit modal:', error);\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                icon: 'error',\r\n");
      out.write("                title: 'Error',\r\n");
      out.write("                text: 'Error opening edit form. Please try again.'\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function deleteNote(id, type) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            title: 'Are you sure?',\r\n");
      out.write("            text: \"You won't be able to revert this!\",\r\n");
      out.write("            icon: 'warning',\r\n");
      out.write("            showCancelButton: true,\r\n");
      out.write("            confirmButtonColor: '#dc3545',\r\n");
      out.write("            cancelButtonColor: '#6c757d',\r\n");
      out.write("            confirmButtonText: 'Yes, delete it!'\r\n");
      out.write("        }).then((result) => {\r\n");
      out.write("            if (result.isConfirmed) {\r\n");
      out.write("                window.location.href = 'DeleteNoteServlet?id=' + id + '&noteType=' + type;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function resetRecordingUI() {\r\n");
      out.write("        document.getElementById('recordButton').disabled = false;\r\n");
      out.write("        document.getElementById('stopButton').disabled = true;\r\n");
      out.write("        document.getElementById('playButton').disabled = true;\r\n");
      out.write("        document.getElementById('recordingStatus').textContent = '';\r\n");
      out.write("        document.getElementById('recordedAudio').style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Voice recording functionality\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const recordButton = document.getElementById('recordButton');\r\n");
      out.write("        const stopButton = document.getElementById('stopButton');\r\n");
      out.write("        const playButton = document.getElementById('playButton');\r\n");
      out.write("        const recordingStatus = document.getElementById('recordingStatus');\r\n");
      out.write("        const recordedAudio = document.getElementById('recordedAudio');\r\n");
      out.write("        const recordedAudioData = document.getElementById('recordedAudioData');\r\n");
      out.write("        \r\n");
      out.write("        if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {\r\n");
      out.write("            recordButton.addEventListener('click', startRecording);\r\n");
      out.write("            stopButton.addEventListener('click', stopRecording);\r\n");
      out.write("            playButton.addEventListener('click', playRecording);\r\n");
      out.write("        } else {\r\n");
      out.write("            recordButton.disabled = true;\r\n");
      out.write("            recordingStatus.textContent = 'Recording not supported in this browser';\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function startRecording() {\r\n");
      out.write("            recordingStatus.innerHTML = '<i class=\"fas fa-circle text-danger\"></i> Recording...';\r\n");
      out.write("            recordButton.disabled = true;\r\n");
      out.write("            stopButton.disabled = false;\r\n");
      out.write("            playButton.disabled = true;\r\n");
      out.write("            recordedAudio.style.display = 'none';\r\n");
      out.write("            \r\n");
      out.write("            navigator.mediaDevices.getUserMedia({ audio: true })\r\n");
      out.write("                .then(stream => {\r\n");
      out.write("                    mediaRecorder = new MediaRecorder(stream);\r\n");
      out.write("                    audioChunks = [];\r\n");
      out.write("                    \r\n");
      out.write("                    mediaRecorder.addEventListener('dataavailable', event => {\r\n");
      out.write("                        audioChunks.push(event.data);\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    mediaRecorder.addEventListener('stop', () => {\r\n");
      out.write("                        audioBlob = new Blob(audioChunks, { type: 'audio/mpeg' });\r\n");
      out.write("                        audioUrl = URL.createObjectURL(audioBlob);\r\n");
      out.write("                        recordedAudio.src = audioUrl;\r\n");
      out.write("                        recordedAudio.style.display = 'block';\r\n");
      out.write("                        \r\n");
      out.write("                        // Convert to base64 for form submission\r\n");
      out.write("                        const reader = new FileReader();\r\n");
      out.write("                        reader.onloadend = function() {\r\n");
      out.write("                            recordedAudioData.value = reader.result;\r\n");
      out.write("                        };\r\n");
      out.write("                        reader.readAsDataURL(audioBlob);\r\n");
      out.write("                        \r\n");
      out.write("                        recordingStatus.innerHTML = '<i class=\"fas fa-check text-success\"></i> Recording saved';\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    mediaRecorder.start();\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => {\r\n");
      out.write("                    console.error('Error accessing microphone:', error);\r\n");
      out.write("                    recordingStatus.innerHTML = '<i class=\"fas fa-exclamation-triangle text-warning\"></i> Error accessing microphone';\r\n");
      out.write("                    recordButton.disabled = false;\r\n");
      out.write("                });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function stopRecording() {\r\n");
      out.write("            mediaRecorder.stop();\r\n");
      out.write("            recordButton.disabled = false;\r\n");
      out.write("            stopButton.disabled = true;\r\n");
      out.write("            playButton.disabled = false;\r\n");
      out.write("            \r\n");
      out.write("            // Stop all audio tracks\r\n");
      out.write("            mediaRecorder.stream.getTracks().forEach(track => track.stop());\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function playRecording() {\r\n");
      out.write("            recordedAudio.play();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Handle audio loading errors\r\n");
      out.write("        const audioElements = document.querySelectorAll('audio');\r\n");
      out.write("        audioElements.forEach(function(audio) {\r\n");
      out.write("            audio.addEventListener('error', function() {\r\n");
      out.write("                const errorMsg = document.createElement('div');\r\n");
      out.write("                errorMsg.className = 'alert alert-warning mt-2';\r\n");
      out.write("                errorMsg.innerHTML = '<small><i class=\"fas fa-exclamation-triangle\"></i> Audio file could not be loaded</small>';\r\n");
      out.write("                audio.parentNode.insertBefore(errorMsg, audio.nextSibling);\r\n");
      out.write("                audio.style.display = 'none';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
