/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-14 07:02:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Reminder;
import model.ToDoItem;
import model.Activity;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Calendar;

public final class reminder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("model.Reminder");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("model.ToDoItem");
    _jspx_imports_classes.add("model.Activity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-bell\"></i>\r\n");
      out.write("            Reminders\r\n");
      out.write("        </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "User" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

@SuppressWarnings("unchecked")
List<Reminder> reminderList = (List<Reminder>) request.getAttribute("reminderList");
@SuppressWarnings("unchecked")
List<ToDoItem> todoItemList = (List<ToDoItem>) request.getAttribute("todoItemList");
@SuppressWarnings("unchecked")
List<Activity> activityList = (List<Activity>) request.getAttribute("activityList");

if (reminderList != null && !reminderList.isEmpty()) {
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
    SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, MMM dd, yyyy");
    SimpleDateFormat fullFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm");
    
    // Group reminders by date
    Calendar today = Calendar.getInstance();
    Calendar tomorrow = Calendar.getInstance();
    tomorrow.add(Calendar.DAY_OF_MONTH, 1);
    
    // Today's reminders
    boolean hasToday = false;
    for (Reminder reminder : reminderList) {
        Calendar reminderCal = Calendar.getInstance();
        reminderCal.setTime(reminder.getTime());
        if (reminderCal.get(Calendar.YEAR) == today.get(Calendar.YEAR) &&
            reminderCal.get(Calendar.DAY_OF_YEAR) == today.get(Calendar.DAY_OF_YEAR)) {
            if (!hasToday) {

      out.write("\r\n");
      out.write("                <div class=\"section-title\">\r\n");
      out.write("                    <i class=\"fas fa-sun section-icon\" style=\"color: #28a745;\"></i>\r\n");
      out.write("                    Today's Reminders\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reminder-grid\">\r\n");

                hasToday = true;
            }

      out.write("\r\n");
      out.write("            <div class=\"reminder-card\">\r\n");
      out.write("                ");
 if (reminder.getType() != null && !reminder.getType().isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"type-badge ");
      out.print( "activity".equals(reminder.getType()) ? "activity" : "" );
      out.write("\">\r\n");
      out.write("                        ");
      out.print( reminder.getType() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"reminder-actions\">\r\n");
      out.write("                    <button class=\"action-btn edit-btn\" onclick=\"editReminder(");
      out.print( reminder.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( fullFormat.format(reminder.getTime()) );
      out.write("', '");
      out.print( reminder.getMessage().replace("'", "\\'") );
      out.write("', '");
      out.print( reminder.getType() != null ? reminder.getType() : "" );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( reminder.getIdtask() );
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"action-btn delete-btn\" onclick=\"deleteReminder(");
      out.print( reminder.getId() );
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"reminder-title\">");
      out.print( reminder.getMessage() );
      out.write("</div>\r\n");
      out.write("                <div class=\"reminder-time\">");
      out.print( timeFormat.format(reminder.getTime()) );
      out.write("</div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (reminder.getIdtask() > 0 && reminder.getType() != null) {
                    String linkedTaskTitle = "";
                    
                    if ("todoitem".equals(reminder.getType()) && todoItemList != null) {
                        for (ToDoItem todo : todoItemList) {
                            if (todo.getId() == reminder.getIdtask()) {
                                linkedTaskTitle = todo.getTitle();
                                break;
                            }
                        }
                    } else if ("activity".equals(reminder.getType()) && activityList != null) {
                        for (Activity activity : activityList) {
                            if (activity.getId() == reminder.getIdtask()) {
                                linkedTaskTitle = activity.getTitle();
                                break;
                            }
                        }
                    }
                    
                    if (!linkedTaskTitle.isEmpty()) {
                
      out.write("\r\n");
      out.write("                    <div class=\"task-link\">Linked to: ");
      out.print( linkedTaskTitle );
      out.write("</div>\r\n");
      out.write("                ");
 } } 
      out.write("\r\n");
      out.write("            </div>\r\n");

        }
    }
    if (hasToday) {

      out.write("\r\n");
      out.write("                </div>\r\n");

    }
    
    // Tomorrow's reminders
    boolean hasTomorrow = false;
    for (Reminder reminder : reminderList) {
        Calendar reminderCal = Calendar.getInstance();
        reminderCal.setTime(reminder.getTime());
        if (reminderCal.get(Calendar.YEAR) == tomorrow.get(Calendar.YEAR) &&
            reminderCal.get(Calendar.DAY_OF_YEAR) == tomorrow.get(Calendar.DAY_OF_YEAR)) {
            if (!hasTomorrow) {

      out.write("\r\n");
      out.write("                <div class=\"section-title\">\r\n");
      out.write("                    <i class=\"fas fa-calendar-day section-icon\" style=\"color: #ffc107;\"></i>\r\n");
      out.write("                    Tomorrow's Reminders\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reminder-grid\">\r\n");

                hasTomorrow = true;
            }

      out.write("\r\n");
      out.write("            <div class=\"reminder-card\">\r\n");
      out.write("                ");
 if (reminder.getType() != null && !reminder.getType().isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"type-badge ");
      out.print( "activity".equals(reminder.getType()) ? "activity" : "" );
      out.write("\">\r\n");
      out.write("                        ");
      out.print( reminder.getType() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"reminder-actions\">\r\n");
      out.write("                    <button class=\"action-btn edit-btn\" onclick=\"editReminder(");
      out.print( reminder.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( fullFormat.format(reminder.getTime()) );
      out.write("', '");
      out.print( reminder.getMessage().replace("'", "\\'") );
      out.write("', '");
      out.print( reminder.getType() != null ? reminder.getType() : "" );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( reminder.getIdtask() );
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"action-btn delete-btn\" onclick=\"deleteReminder(");
      out.print( reminder.getId() );
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"reminder-title\">");
      out.print( reminder.getMessage() );
      out.write("</div>\r\n");
      out.write("                <div class=\"reminder-time\">");
      out.print( timeFormat.format(reminder.getTime()) );
      out.write("</div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (reminder.getIdtask() > 0 && reminder.getType() != null) {
                    String linkedTaskTitle = "";
                    
                    if ("todoitem".equals(reminder.getType()) && todoItemList != null) {
                        for (ToDoItem todo : todoItemList) {
                            if (todo.getId() == reminder.getIdtask()) {
                                linkedTaskTitle = todo.getTitle();
                                break;
                            }
                        }
                    } else if ("activity".equals(reminder.getType()) && activityList != null) {
                        for (Activity activity : activityList) {
                            if (activity.getId() == reminder.getIdtask()) {
                                linkedTaskTitle = activity.getTitle();
                                break;
                            }
                        }
                    }
                    
                    if (!linkedTaskTitle.isEmpty()) {
                
      out.write("\r\n");
      out.write("                    <div class=\"task-link\">Linked to: ");
      out.print( linkedTaskTitle );
      out.write("</div>\r\n");
      out.write("                ");
 } } 
      out.write("\r\n");
      out.write("            </div>\r\n");

        }
    }
    if (hasTomorrow) {

      out.write("\r\n");
      out.write("                </div>\r\n");

    }
    
    // Other reminders
    boolean hasOther = false;
    for (Reminder reminder : reminderList) {
        Calendar reminderCal = Calendar.getInstance();
        reminderCal.setTime(reminder.getTime());
        if ((reminderCal.get(Calendar.YEAR) != today.get(Calendar.YEAR) ||
            reminderCal.get(Calendar.DAY_OF_YEAR) != today.get(Calendar.DAY_OF_YEAR)) &&
            (reminderCal.get(Calendar.YEAR) != tomorrow.get(Calendar.YEAR) ||
            reminderCal.get(Calendar.DAY_OF_YEAR) != tomorrow.get(Calendar.DAY_OF_YEAR))) {
            if (!hasOther) {

      out.write("\r\n");
      out.write("                <div class=\"section-title\">\r\n");
      out.write("                    <i class=\"fas fa-calendar-alt section-icon\" style=\"color: #6c757d;\"></i>\r\n");
      out.write("                    Other Reminders\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"reminder-grid\">\r\n");

                hasOther = true;
            }

      out.write("\r\n");
      out.write("            <div class=\"reminder-card\">\r\n");
      out.write("                ");
 if (reminder.getType() != null && !reminder.getType().isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"type-badge ");
      out.print( "activity".equals(reminder.getType()) ? "activity" : "" );
      out.write("\">\r\n");
      out.write("                        ");
      out.print( reminder.getType() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"reminder-actions\">\r\n");
      out.write("                    <button class=\"action-btn edit-btn\" onclick=\"editReminder(");
      out.print( reminder.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( fullFormat.format(reminder.getTime()) );
      out.write("', '");
      out.print( reminder.getMessage().replace("'", "\\'") );
      out.write("', '");
      out.print( reminder.getType() != null ? reminder.getType() : "" );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( reminder.getIdtask() );
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"action-btn delete-btn\" onclick=\"deleteReminder(");
      out.print( reminder.getId() );
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"reminder-title\">");
      out.print( reminder.getMessage() );
      out.write("</div>\r\n");
      out.write("                <div class=\"reminder-time\">");
      out.print( timeFormat.format(reminder.getTime()) );
      out.write("</div>\r\n");
      out.write("                <div class=\"reminder-date\">");
      out.print( dateFormat.format(reminder.getTime()) );
      out.write("</div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (reminder.getIdtask() > 0 && reminder.getType() != null) {
                    String linkedTaskTitle = "";
                    
                    if ("todoitem".equals(reminder.getType()) && todoItemList != null) {
                        for (ToDoItem todo : todoItemList) {
                            if (todo.getId() == reminder.getIdtask()) {
                                linkedTaskTitle = todo.getTitle();
                                break;
                            }
                        }
                    } else if ("activity".equals(reminder.getType()) && activityList != null) {
                        for (Activity activity : activityList) {
                            if (activity.getId() == reminder.getIdtask()) {
                                linkedTaskTitle = activity.getTitle();
                                break;
                            }
                        }
                    }
                    
                    if (!linkedTaskTitle.isEmpty()) {
                
      out.write("\r\n");
      out.write("                    <div class=\"task-link\">Linked to: ");
      out.print( linkedTaskTitle );
      out.write("</div>\r\n");
      out.write("                ");
 } } 
      out.write("\r\n");
      out.write("            </div>\r\n");

        }
    }
    if (hasOther) {

      out.write("\r\n");
      out.write("                </div>\r\n");

    }
} else {

      out.write("\r\n");
      out.write("    <div class=\"empty-state\">\r\n");
      out.write("        <i class=\"fas fa-bell fa-3x\"></i>\r\n");
      out.write("        <h3>No Reminders Yet</h3>\r\n");
      out.write("        <p>Create reminders to stay on top of your tasks and activities</p>\r\n");
      out.write("        <button class=\"btn btn-primary mt-3\" onclick=\"showAddModalReminder()\">\r\n");
      out.write("            <i class=\"fas fa-plus\"></i> Add Reminder\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<button class=\"floating-add-btn\" onclick=\"showAddModalReminder()\">\r\n");
      out.write("    <i class=\"fas fa-plus\"></i>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Reminder Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addReminderModal\" tabindex=\"-1\" aria-labelledby=\"addReminderModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"addReminderModalLabel\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add New Reminder\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"AddReminderServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"message\" class=\"form-label\">Reminder Message</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"message\" name=\"message\" placeholder=\"Enter reminder message\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"time\" class=\"form-label\">Date & Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"time\" name=\"time\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"type\" class=\"form-label\">Link to Task (Optional)</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"type\" name=\"type\" onchange=\"updateTaskOptions()\">\r\n");
      out.write("                            <option value=\"\">No task linked</option>\r\n");
      out.write("                            <option value=\"todoitem\">To-Do Item</option>\r\n");
      out.write("                            <option value=\"activity\">Activity</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\" id=\"taskSelectGroup\" style=\"display: none;\">\r\n");
      out.write("                        <label for=\"idtask\" class=\"form-label\">Select Task</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"idtask\" name=\"idtask\">\r\n");
      out.write("                            <option value=\"0\">Select a task</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save\"></i> Save Reminder\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Reminder Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editReminderModal\" tabindex=\"-1\" aria-labelledby=\"editReminderModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"editReminderModalLabel\">\r\n");
      out.write("                    <i class=\"fas fa-edit\"></i> Edit Reminder\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditReminderServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" id=\"editId\" name=\"id\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"editMessage\" class=\"form-label\">Reminder Message</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editMessage\" name=\"message\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"editTime\" class=\"form-label\">Date & Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"editTime\" name=\"time\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\">\r\n");
      out.write("                        <label for=\"editType\" class=\"form-label\">Link to Task (Optional)</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"editType\" name=\"type\" onchange=\"updateEditTaskOptions()\">\r\n");
      out.write("                            <option value=\"\">No task linked</option>\r\n");
      out.write("                            <option value=\"todoitem\">To-Do Item</option>\r\n");
      out.write("                            <option value=\"activity\">Activity</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group mb-3\" id=\"editTaskSelectGroup\" style=\"display: none;\">\r\n");
      out.write("                        <label for=\"editIdtask\" class=\"form-label\">Select Task</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"editIdtask\" name=\"idtask\">\r\n");
      out.write("                            <option value=\"0\">Select a task</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save\"></i> Update Reminder\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Task data for JavaScript\r\n");
      out.write("    const todoItems = [\r\n");
      out.write("        ");

        if (todoItemList != null) {
            for (int i = 0; i < todoItemList.size(); i++) {
                ToDoItem todo = todoItemList.get(i);
        
      out.write("\r\n");
      out.write("            {id: ");
      out.print( todo.getId() );
      out.write(", title: \"");
      out.print( todo.getTitle().replace("\"", "\\\"") );
      out.write("\"}\r\n");
      out.write("            ");
      out.print( i < todoItemList.size() - 1 ? "," : "" );
      out.write("\r\n");
      out.write("        ");

            }
        }
        
      out.write("\r\n");
      out.write("    ];\r\n");
      out.write("    \r\n");
      out.write("    const activities = [\r\n");
      out.write("        ");

        if (activityList != null) {
            for (int i = 0; i < activityList.size(); i++) {
                Activity activity = activityList.get(i);
        
      out.write("\r\n");
      out.write("            {id: ");
      out.print( activity.getId() );
      out.write(", title: \"");
      out.print( activity.getTitle().replace("\"", "\\\"") );
      out.write("\"}\r\n");
      out.write("            ");
      out.print( i < activityList.size() - 1 ? "," : "" );
      out.write("\r\n");
      out.write("        ");

            }
        }
        
      out.write("\r\n");
      out.write("    ];\r\n");
      out.write("\r\n");
      out.write("    // Set default time to now + 1 hour\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        // SweetAlert2 is now available for delete confirmations\r\n");
      out.write("        console.log('Reminder page loaded successfully');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function showAddModalReminder() {\r\n");
      out.write("        // Reset form\r\n");
      out.write("        document.getElementById('message').value = '';\r\n");
      out.write("        document.getElementById('type').value = '';\r\n");
      out.write("        document.getElementById('idtask').value = '0';\r\n");
      out.write("        document.getElementById('taskSelectGroup').style.display = 'none';\r\n");
      out.write("        \r\n");
      out.write("        // Set default time to now + 1 hour\r\n");
      out.write("        const now = new Date();\r\n");
      out.write("        now.setHours(now.getHours() + 1);\r\n");
      out.write("        const formattedDate = now.toISOString().slice(0, 16);\r\n");
      out.write("        document.getElementById('time').value = formattedDate;\r\n");
      out.write("        \r\n");
      out.write("        const modal = new bootstrap.Modal(document.getElementById('addReminderModal'));\r\n");
      out.write("        modal.show();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function deleteReminder(id) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            title: 'Are you sure?',\r\n");
      out.write("            text: \"You won't be able to revert this!\",\r\n");
      out.write("            icon: 'warning',\r\n");
      out.write("            showCancelButton: true,\r\n");
      out.write("            confirmButtonColor: '#dc3545',\r\n");
      out.write("            cancelButtonColor: '#6c757d',\r\n");
      out.write("            confirmButtonText: 'Yes, delete it!',\r\n");
      out.write("            cancelButtonText: 'Cancel'\r\n");
      out.write("        }).then((result) => {\r\n");
      out.write("            if (result.isConfirmed) {\r\n");
      out.write("                window.location.href = 'DeleteReminderServlet?id=' + id;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function editReminder(id, time, message, type, idtask) {\r\n");
      out.write("        document.getElementById('editId').value = id;\r\n");
      out.write("        document.getElementById('editTime').value = time;\r\n");
      out.write("        document.getElementById('editMessage').value = message;\r\n");
      out.write("        document.getElementById('editType').value = type || '';\r\n");
      out.write("        \r\n");
      out.write("        // Update task options based on type\r\n");
      out.write("        updateEditTaskOptions();\r\n");
      out.write("        \r\n");
      out.write("        // Set selected task if exists\r\n");
      out.write("        if (idtask > 0) {\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                document.getElementById('editIdtask').value = idtask;\r\n");
      out.write("            }, 100);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        const modal = new bootstrap.Modal(document.getElementById('editReminderModal'));\r\n");
      out.write("        modal.show();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function updateTaskOptions() {\r\n");
      out.write("        const typeSelect = document.getElementById('type');\r\n");
      out.write("        const taskSelect = document.getElementById('idtask');\r\n");
      out.write("        const taskSelectGroup = document.getElementById('taskSelectGroup');\r\n");
      out.write("        const selectedType = typeSelect.value;\r\n");
      out.write("        \r\n");
      out.write("        if (!selectedType) {\r\n");
      out.write("            taskSelectGroup.style.display = 'none';\r\n");
      out.write("            taskSelect.value = '0';\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        taskSelectGroup.style.display = 'block';\r\n");
      out.write("        taskSelect.innerHTML = '<option value=\"0\">Select a task</option>';\r\n");
      out.write("        \r\n");
      out.write("        if (selectedType === 'todoitem') {\r\n");
      out.write("            todoItems.forEach(todo => {\r\n");
      out.write("                const optionElement = document.createElement('option');\r\n");
      out.write("                optionElement.value = todo.id;\r\n");
      out.write("                optionElement.textContent = todo.title;\r\n");
      out.write("                taskSelect.appendChild(optionElement);\r\n");
      out.write("            });\r\n");
      out.write("        } else if (selectedType === 'activity') {\r\n");
      out.write("            activities.forEach(activity => {\r\n");
      out.write("                const optionElement = document.createElement('option');\r\n");
      out.write("                optionElement.value = activity.id;\r\n");
      out.write("                optionElement.textContent = activity.title;\r\n");
      out.write("                taskSelect.appendChild(optionElement);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function updateEditTaskOptions() {\r\n");
      out.write("        const typeSelect = document.getElementById('editType');\r\n");
      out.write("        const taskSelect = document.getElementById('editIdtask');\r\n");
      out.write("        const taskSelectGroup = document.getElementById('editTaskSelectGroup');\r\n");
      out.write("        const selectedType = typeSelect.value;\r\n");
      out.write("        \r\n");
      out.write("        if (!selectedType) {\r\n");
      out.write("            taskSelectGroup.style.display = 'none';\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        taskSelectGroup.style.display = 'block';\r\n");
      out.write("        taskSelect.innerHTML = '<option value=\"0\">Select a task</option>';\r\n");
      out.write("        \r\n");
      out.write("        if (selectedType === 'todoitem') {\r\n");
      out.write("            todoItems.forEach(todo => {\r\n");
      out.write("                const optionElement = document.createElement('option');\r\n");
      out.write("                optionElement.value = todo.id;\r\n");
      out.write("                optionElement.textContent = todo.title;\r\n");
      out.write("                taskSelect.appendChild(optionElement);\r\n");
      out.write("            });\r\n");
      out.write("        } else if (selectedType === 'activity') {\r\n");
      out.write("            activities.forEach(activity => {\r\n");
      out.write("                const optionElement = document.createElement('option');\r\n");
      out.write("                optionElement.value = activity.id;\r\n");
      out.write("                optionElement.textContent = activity.title;\r\n");
      out.write("                taskSelect.appendChild(optionElement);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
