/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-12 19:50:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import config.DB;
import java.sql.ResultSet;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("config.DB");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Get current user's notification settings
Integer userIdObj = (Integer) session.getAttribute("userId");
if (userIdObj == null) {
    response.sendRedirect("login_page.jsp");
    return;
}
int userId = userIdObj.intValue();

DB db = new DB();
db.connect();

int alarmSound = 1;
int notificationSound = 1;

try {
    // Get alarm sound setting
    String alarmQuery = "SELECT sound FROM notification_settings WHERE user_id = " + userId + " AND type = 'Alarm'";
    ResultSet alarmRs = db.getData(alarmQuery);
    if (alarmRs != null && alarmRs.next()) {
        alarmSound = alarmRs.getInt("sound");
    }
    
    // Get notification sound setting
    String notifQuery = "SELECT sound FROM notification_settings WHERE user_id = " + userId + " AND type = 'Notification'";
    ResultSet notifRs = db.getData(notifQuery);
    if (notifRs != null && notifRs.next()) {
        notificationSound = notifRs.getInt("sound");
    }
} catch (Exception e) {
    System.err.println("Error getting notification settings: " + e.getMessage());
    e.printStackTrace();
} finally {
    db.disconnect();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-cog\"></i>\r\n");
      out.write("            Settings\r\n");
      out.write("        </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "User" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Settings Grid -->\r\n");
      out.write("<div class=\"settings-grid\">\r\n");
      out.write("    <!-- Profile Setting Card -->\r\n");
      out.write("    <div class=\"settings-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <div class=\"card-icon\">\r\n");
      out.write("                <i class=\"fas fa-user\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"card-title\">Profile Setting</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"profile-picture-section\">\r\n");
      out.write("            <div class=\"profile-picture\">\r\n");
      out.write("                <i class=\"fas fa-user\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"updateProfile\" method=\"post\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label class=\"form-label\">Username</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"username\" value=\"");
      out.print( session.getAttribute("username") );
      out.write("\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label class=\"form-label\">Email</label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"email\" value=\"");
      out.print( session.getAttribute("email") );
      out.write("\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label class=\"form-label\">Password</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"newPassword\" placeholder=\"••••••••••\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"HomeServlet?page=edit_profile\" class=\"btn btn-primary\">\r\n");
      out.write("                <i class=\"fas fa-edit\"></i> Edit Profile\r\n");
      out.write("            </a>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Notification Setting Card -->\r\n");
      out.write("    <div class=\"settings-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <div class=\"card-icon\">\r\n");
      out.write("                <i class=\"fas fa-bell\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"card-title\">Notification Setting</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group mb-3\">\r\n");
      out.write("            <label for=\"alarmSoundSelect\" class=\"form-label\">Alarm Ringtone</label>\r\n");
      out.write("            <select class=\"form-control\" id=\"alarmSoundSelect\">\r\n");
      out.write("                <option value=\"1\" ");
      out.print( alarmSound == 1 ? "selected" : "" );
      out.write(">Classic Alarm</option>\r\n");
      out.write("                <option value=\"2\" ");
      out.print( alarmSound == 2 ? "selected" : "" );
      out.write(">Morning Bell</option>\r\n");
      out.write("                <option value=\"3\" ");
      out.print( alarmSound == 3 ? "selected" : "" );
      out.write(">Gentle Wake</option>\r\n");
      out.write("                <option value=\"4\" ");
      out.print( alarmSound == 4 ? "selected" : "" );
      out.write(">Digital Beep</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-sm btn-outline-primary mt-2\" id=\"previewAlarmBtn\" onclick=\"previewAlarmSound()\">\r\n");
      out.write("                <i class=\"fas fa-play\"></i> Preview Alarm Sound\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group mb-3\">\r\n");
      out.write("            <label for=\"notificationSoundSelect\" class=\"form-label\">Reminder Notification Sound</label>\r\n");
      out.write("            <select class=\"form-control\" id=\"notificationSoundSelect\">\r\n");
      out.write("                <option value=\"1\" ");
      out.print( notificationSound == 1 ? "selected" : "" );
      out.write(">Soft Chime</option>\r\n");
      out.write("                <option value=\"2\" ");
      out.print( notificationSound == 2 ? "selected" : "" );
      out.write(">Notification Bell</option>\r\n");
      out.write("                <option value=\"3\" ");
      out.print( notificationSound == 3 ? "selected" : "" );
      out.write(">Gentle Ping</option>\r\n");
      out.write("                <option value=\"4\" ");
      out.print( notificationSound == 4 ? "selected" : "" );
      out.write(">Alert Tone</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-sm btn-outline-primary mt-2\" id=\"previewNotificationBtn\" onclick=\"previewNotificationSound()\">\r\n");
      out.write("                <i class=\"fas fa-play\"></i> Preview Notification Sound\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" onclick=\"updateNotificationSettings()\">\r\n");
      out.write("            <i class=\"fas fa-save\"></i> Save Settings\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Danger Zone Card - Full width -->\r\n");
      out.write("    <div class=\"settings-card full-width\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <div class=\"card-icon\" style=\"background-color: #dc3545;\">\r\n");
      out.write("                <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 class=\"card-title\">Danger Zone</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger w-100 mb-3\" onclick=\"confirmLogout()\">\r\n");
      out.write("                    <i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger w-100 mb-3\" onclick=\"confirmDeleteAccount()\">\r\n");
      out.write("                    <i class=\"fas fa-trash\"></i> Delete Account\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Audio elements for preview -->\r\n");
      out.write("<audio id=\"previewAudio\" preload=\"none\"></audio>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Global variables for audio control\r\n");
      out.write("let currentPreviewTimeout = null;\r\n");
      out.write("let isPreviewPlaying = false;\r\n");
      out.write("\r\n");
      out.write("// Debug function to check if elements exist\r\n");
      out.write("function checkElements() {\r\n");
      out.write("    const alarmSelect = document.getElementById('alarmSoundSelect');\r\n");
      out.write("    const notificationSelect = document.getElementById('notificationSoundSelect');\r\n");
      out.write("    \r\n");
      out.write("    console.log('Alarm select element:', alarmSelect);\r\n");
      out.write("    console.log('Notification select element:', notificationSelect);\r\n");
      out.write("    \r\n");
      out.write("    if (alarmSelect) {\r\n");
      out.write("        console.log('Alarm select value:', alarmSelect.value);\r\n");
      out.write("    } else {\r\n");
      out.write("        console.error('Alarm select element not found!');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (notificationSelect) {\r\n");
      out.write("        console.log('Notification select value:', notificationSelect.value);\r\n");
      out.write("    } else {\r\n");
      out.write("        console.error('Notification select element not found!');\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Stop current preview\r\n");
      out.write("function stopCurrentPreview() {\r\n");
      out.write("    const audio = document.getElementById('previewAudio');\r\n");
      out.write("    if (audio) {\r\n");
      out.write("        audio.pause();\r\n");
      out.write("        audio.currentTime = 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (currentPreviewTimeout) {\r\n");
      out.write("        clearTimeout(currentPreviewTimeout);\r\n");
      out.write("        currentPreviewTimeout = null;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    isPreviewPlaying = false;\r\n");
      out.write("    \r\n");
      out.write("    // Reset button texts\r\n");
      out.write("    const alarmBtn = document.getElementById('previewAlarmBtn');\r\n");
      out.write("    const notificationBtn = document.getElementById('previewNotificationBtn');\r\n");
      out.write("    \r\n");
      out.write("    if (alarmBtn) {\r\n");
      out.write("        alarmBtn.innerHTML = '<i class=\"fas fa-play\"></i> Preview Alarm Sound';\r\n");
      out.write("        alarmBtn.disabled = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (notificationBtn) {\r\n");
      out.write("        notificationBtn.innerHTML = '<i class=\"fas fa-play\"></i> Preview Notification Sound';\r\n");
      out.write("        notificationBtn.disabled = false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Preview alarm sound function\r\n");
      out.write("function previewAlarmSound() {\r\n");
      out.write("    if (isPreviewPlaying) {\r\n");
      out.write("        stopCurrentPreview();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const alarmSelect = document.getElementById('alarmSoundSelect');\r\n");
      out.write("    if (!alarmSelect) {\r\n");
      out.write("        console.error('Alarm select element not found');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const soundNumber = alarmSelect.value;\r\n");
      out.write("    console.log('Previewing alarm sound:', soundNumber);\r\n");
      out.write("    \r\n");
      out.write("    // Validate sound number\r\n");
      out.write("    if (!soundNumber || soundNumber === '' || soundNumber === 'undefined') {\r\n");
      out.write("        console.error('Invalid sound number:', soundNumber);\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    playSound(soundNumber, 'alarm');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Preview notification sound function\r\n");
      out.write("function previewNotificationSound() {\r\n");
      out.write("    if (isPreviewPlaying) {\r\n");
      out.write("        stopCurrentPreview();\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const notificationSelect = document.getElementById('notificationSoundSelect');\r\n");
      out.write("    if (!notificationSelect) {\r\n");
      out.write("        console.error('Notification select element not found');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const soundNumber = notificationSelect.value;\r\n");
      out.write("    console.log('Previewing notification sound:', soundNumber);\r\n");
      out.write("    \r\n");
      out.write("    // Validate sound number\r\n");
      out.write("    if (!soundNumber || soundNumber === '' || soundNumber === 'undefined') {\r\n");
      out.write("        console.error('Invalid sound number:', soundNumber);\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    playSound(soundNumber, 'notification');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Play sound function with 7-second limit\r\n");
      out.write("function playSound(soundNumber, type) {\r\n");
      out.write("    // Ensure soundNumber is a string and not empty\r\n");
      out.write("    const soundNum = String(soundNumber).trim();\r\n");
      out.write("    \r\n");
      out.write("    if (!soundNum || soundNum === '' || soundNum === 'undefined' || soundNum === 'null') {\r\n");
      out.write("        console.error('Invalid sound number for playSound:', soundNumber);\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Error',\r\n");
      out.write("            text: 'Invalid sound selection. Please select a valid sound.',\r\n");
      out.write("            timer: 3000,\r\n");
      out.write("            showConfirmButton: false\r\n");
      out.write("        });\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const audio = document.getElementById('previewAudio');\r\n");
      out.write("    \r\n");
      out.write("    // Build the sound path using proper string concatenation\r\n");
      out.write("    let soundPath;\r\n");
      out.write("    if (type === 'alarm'){\r\n");
      out.write("        soundPath = 'assets/sound/alarm/' + soundNum + '.mp3';\r\n");
      out.write("    } else {\r\n");
      out.write("        soundPath = 'assets/sound/notif/' + soundNum + '.mp3';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    console.log('Playing sound:', soundPath, 'for type:', type);\r\n");
      out.write("    console.log('Sound number used:', soundNum);\r\n");
      out.write("    \r\n");
      out.write("    // Stop any current preview\r\n");
      out.write("    stopCurrentPreview();\r\n");
      out.write("    \r\n");
      out.write("    // Set playing state\r\n");
      out.write("    isPreviewPlaying = true;\r\n");
      out.write("    \r\n");
      out.write("    // Update button text based on type\r\n");
      out.write("    const btnId = type === 'alarm' ? 'previewAlarmBtn' : 'previewNotificationBtn';\r\n");
      out.write("    const btn = document.getElementById(btnId);\r\n");
      out.write("    if (btn) {\r\n");
      out.write("        btn.innerHTML = '<i class=\"fas fa-stop\"></i> Stop Preview';\r\n");
      out.write("        btn.disabled = false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Set the source and load\r\n");
      out.write("    audio.src = soundPath;\r\n");
      out.write("    audio.load(); // Force reload\r\n");
      out.write("    \r\n");
      out.write("    // Attempt to play\r\n");
      out.write("    const playPromise = audio.play();\r\n");
      out.write("    \r\n");
      out.write("    if (playPromise !== undefined) {\r\n");
      out.write("        playPromise.then(() => {\r\n");
      out.write("            console.log('Audio playing successfully');\r\n");
      out.write("            \r\n");
      out.write("            // Set timeout to stop after 7 seconds\r\n");
      out.write("            currentPreviewTimeout = setTimeout(() => {\r\n");
      out.write("                console.log('Stopping preview after 7 seconds');\r\n");
      out.write("                stopCurrentPreview();\r\n");
      out.write("            }, 7000); // 7 seconds\r\n");
      out.write("            \r\n");
      out.write("        }).catch(e => {\r\n");
      out.write("            console.error('Error playing preview sound:', e);\r\n");
      out.write("            console.error('Failed sound path:', soundPath);\r\n");
      out.write("            stopCurrentPreview();\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                icon: 'warning',\r\n");
      out.write("                title: 'Audio Preview',\r\n");
      out.write("                text: `Could not play ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" sound ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${soundNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(". Audio file may not exist: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${soundPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`,\r\n");
      out.write("                timer: 4000,\r\n");
      out.write("                showConfirmButton: false\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Also stop when audio ends naturally\r\n");
      out.write("    audio.addEventListener('ended', stopCurrentPreview, { once: true });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Update notification settings with proper form data\r\n");
      out.write("function updateNotificationSettings() {\r\n");
      out.write("    // Check elements first\r\n");
      out.write("    checkElements();\r\n");
      out.write("    \r\n");
      out.write("    const alarmSelect = document.getElementById('alarmSoundSelect');\r\n");
      out.write("    const notificationSelect = document.getElementById('notificationSoundSelect');\r\n");
      out.write("    \r\n");
      out.write("    if (!alarmSelect || !notificationSelect) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Error',\r\n");
      out.write("            text: 'Could not find sound selection elements. Please refresh the page.',\r\n");
      out.write("            showConfirmButton: true\r\n");
      out.write("        });\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const alarmSound = alarmSelect.value;\r\n");
      out.write("    const notificationSound = notificationSelect.value;\r\n");
      out.write("    \r\n");
      out.write("    console.log('Updating settings - Alarm:', alarmSound, 'Notification:', notificationSound);\r\n");
      out.write("    \r\n");
      out.write("    // Validate values\r\n");
      out.write("    if (!alarmSound || !notificationSound || alarmSound === '' || notificationSound === '') {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Error',\r\n");
      out.write("            text: 'Please select both alarm and notification sounds.',\r\n");
      out.write("            showConfirmButton: true\r\n");
      out.write("        });\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    Swal.fire({\r\n");
      out.write("        title: 'Updating Settings...',\r\n");
      out.write("        text: 'Please wait while we save your notification preferences.',\r\n");
      out.write("        allowOutsideClick: false,\r\n");
      out.write("        didOpen: () => {\r\n");
      out.write("            Swal.showLoading();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Create URL encoded form data (not FormData for better compatibility)\r\n");
      out.write("    const params = new URLSearchParams();\r\n");
      out.write("    params.append('alarmSound', alarmSound);\r\n");
      out.write("    params.append('notificationSound', notificationSound);\r\n");
      out.write("    \r\n");
      out.write("    console.log('Sending parameters:', params.toString());\r\n");
      out.write("    \r\n");
      out.write("    fetch('UpdateNotificationSettingsServlet', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: {\r\n");
      out.write("            'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("        },\r\n");
      out.write("        body: params.toString()\r\n");
      out.write("    })\r\n");
      out.write("    .then(response => {\r\n");
      out.write("        console.log('Response status:', response.status);\r\n");
      out.write("        if (!response.ok) {\r\n");
      out.write("            throw new Error(`HTTP error! status: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${response.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("        }\r\n");
      out.write("        return response.text();\r\n");
      out.write("    })\r\n");
      out.write("    .then(data => {\r\n");
      out.write("        console.log('Response data:', data);\r\n");
      out.write("        Swal.close();\r\n");
      out.write("        if (data.includes('success')) {\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("                icon: 'success',\r\n");
      out.write("                title: 'Settings Updated!',\r\n");
      out.write("                text: 'Your notification preferences have been saved.',\r\n");
      out.write("                timer: 3000,\r\n");
      out.write("                showConfirmButton: false\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            throw new Error('Update failed: ' + data);\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("    .catch(error => {\r\n");
      out.write("        console.error('Update error:', error);\r\n");
      out.write("        Swal.close();\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Update Failed',\r\n");
      out.write("            text: 'Could not save your settings. Error: ' + error.message,\r\n");
      out.write("            showConfirmButton: true\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Confirmation functions\r\n");
      out.write("function confirmLogout() {\r\n");
      out.write("    Swal.fire({\r\n");
      out.write("        title: 'Are you sure?',\r\n");
      out.write("        text: \"You will be logged out of your account\",\r\n");
      out.write("        icon: 'warning',\r\n");
      out.write("        showCancelButton: true,\r\n");
      out.write("        confirmButtonColor: '#ff3b65',\r\n");
      out.write("        cancelButtonColor: '#6c757d',\r\n");
      out.write("        confirmButtonText: 'Yes, logout!'\r\n");
      out.write("    }).then((result) => {\r\n");
      out.write("        if (result.isConfirmed) {\r\n");
      out.write("            window.location.href = 'logout';\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function confirmDeleteAccount() {\r\n");
      out.write("    Swal.fire({\r\n");
      out.write("        title: 'Delete Account',\r\n");
      out.write("        html: `\r\n");
      out.write("            <div class=\"text-start\">\r\n");
      out.write("                <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                    <strong>Warning!</strong> This action cannot be undone. All your data will be permanently deleted.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"deletePassword\" class=\"form-label\">Enter your password to confirm:</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"deletePassword\" placeholder=\"Password\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"confirmDelete\" class=\"form-label\">Type \"DELETE\" to confirm:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"confirmDelete\" placeholder=\"DELETE\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        `,\r\n");
      out.write("        showCancelButton: true,\r\n");
      out.write("        confirmButtonColor: '#dc3545',\r\n");
      out.write("        cancelButtonColor: '#6c757d',\r\n");
      out.write("        confirmButtonText: 'Delete Account',\r\n");
      out.write("        preConfirm: () => {\r\n");
      out.write("            const password = document.getElementById('deletePassword').value;\r\n");
      out.write("            const confirmText = document.getElementById('confirmDelete').value;\r\n");
      out.write("            \r\n");
      out.write("            if (!password) {\r\n");
      out.write("                Swal.showValidationMessage('Please enter your password');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if (confirmText !== 'DELETE') {\r\n");
      out.write("                Swal.showValidationMessage('Please type \"DELETE\" exactly to confirm');\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            return { password: password, confirmText: confirmText };\r\n");
      out.write("        }\r\n");
      out.write("    }).then((result) => {\r\n");
      out.write("        if (result.isConfirmed) {\r\n");
      out.write("            // Create a form and submit it\r\n");
      out.write("            const form = document.createElement('form');\r\n");
      out.write("            form.method = 'POST';\r\n");
      out.write("            form.action = 'DeleteUserServlet';\r\n");
      out.write("            \r\n");
      out.write("            const passwordInput = document.createElement('input');\r\n");
      out.write("            passwordInput.type = 'hidden';\r\n");
      out.write("            passwordInput.name = 'password';\r\n");
      out.write("            passwordInput.value = result.value.password;\r\n");
      out.write("            \r\n");
      out.write("            const confirmInput = document.createElement('input');\r\n");
      out.write("            confirmInput.type = 'hidden';\r\n");
      out.write("            confirmInput.name = 'confirmDelete';\r\n");
      out.write("            confirmInput.value = result.value.confirmText;\r\n");
      out.write("            \r\n");
      out.write("            form.appendChild(passwordInput);\r\n");
      out.write("            form.appendChild(confirmInput);\r\n");
      out.write("            document.body.appendChild(form);\r\n");
      out.write("            form.submit();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Handle success/error messages with SweetAlert2\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    console.log('DOM loaded, checking elements...');\r\n");
      out.write("    checkElements();\r\n");
      out.write("    \r\n");
      out.write("    const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("    const error = urlParams.get('error');\r\n");
      out.write("    const message = urlParams.get('message');\r\n");
      out.write("\r\n");
      out.write("    if (error) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Error!',\r\n");
      out.write("            text: error,\r\n");
      out.write("            timer: 3000,\r\n");
      out.write("            showConfirmButton: false\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    if (message) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            icon: 'success',\r\n");
      out.write("            title: 'Success!',\r\n");
      out.write("            text: message,\r\n");
      out.write("            timer: 3000,\r\n");
      out.write("            showConfirmButton: false\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
