/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-13 07:43:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import model.ToDoItem;
import model.Activity;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;

public final class task_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("model.ToDoItem");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("model.Activity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"page-title-section\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <i class=\"fas fa-tasks\"></i>\r\n");
      out.write("            Tasks & Activities\r\n");
      out.write("        </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("        <div class=\"profile-info\">\r\n");
      out.write("            <span>");
      out.print( session.getAttribute("username") != null ? session.getAttribute("username") : "User" );
      out.write("</span>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <img src=\"assets/image/Avatar.png\" alt=\"Profile\" class=\"profile-avatar dropdown-toggle\" data-bs-toggle=\"dropdown\" style=\"cursor: pointer;\">\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"UserServlet\">Profile</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

@SuppressWarnings("unchecked")
List<ToDoItem> todoItems = (List<ToDoItem>) request.getAttribute("todoItems");
@SuppressWarnings("unchecked")
List<Activity> activities = (List<Activity>) request.getAttribute("activities");
SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd");

// Get today and tomorrow dates
Calendar cal = Calendar.getInstance();
Date today = cal.getTime();
cal.add(Calendar.DAY_OF_MONTH, 1);
Date tomorrow = cal.getTime();

// Helper method to check if date is today
java.util.function.Function<Date, Boolean> isToday = (date) -> {
    Calendar dateCal = Calendar.getInstance();
    dateCal.setTime(date);
    Calendar todayCal = Calendar.getInstance();
    todayCal.setTime(today);
    return dateCal.get(Calendar.YEAR) == todayCal.get(Calendar.YEAR) &&
           dateCal.get(Calendar.DAY_OF_YEAR) == todayCal.get(Calendar.DAY_OF_YEAR);
};

// Helper method to check if date is tomorrow
java.util.function.Function<Date, Boolean> isTomorrow = (date) -> {
    Calendar dateCal = Calendar.getInstance();
    dateCal.setTime(date);
    Calendar tomorrowCal = Calendar.getInstance();
    tomorrowCal.setTime(tomorrow);
    return dateCal.get(Calendar.YEAR) == tomorrowCal.get(Calendar.YEAR) &&
           dateCal.get(Calendar.DAY_OF_YEAR) == tomorrowCal.get(Calendar.DAY_OF_YEAR);
};

// Separate todos by time
List<ToDoItem> todayTodos = new ArrayList<>();
List<ToDoItem> tomorrowTodos = new ArrayList<>();
List<ToDoItem> otherTodos = new ArrayList<>();

if (todoItems != null) {
    for (ToDoItem todo : todoItems) {
        if (isToday.apply(todo.getDueDate())) {
            todayTodos.add(todo);
        } else if (isTomorrow.apply(todo.getDueDate())) {
            tomorrowTodos.add(todo);
        } else {
            otherTodos.add(todo);
        }
    }
}

// Separate activities by time
List<Activity> todayActivities = new ArrayList<>();
List<Activity> tomorrowActivities = new ArrayList<>();
List<Activity> otherActivities = new ArrayList<>();

if (activities != null) {
    for (Activity activity : activities) {
        if (isToday.apply(activity.getStartTime())) {
            todayActivities.add(activity);
        } else if (isTomorrow.apply(activity.getStartTime())) {
            tomorrowActivities.add(activity);
        } else {
            otherActivities.add(activity);
        }
    }
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Tasks Container with Two Columns -->\r\n");
      out.write("<div class=\"notes-container\">\r\n");
      out.write("    <!-- To-Do Items Column -->\r\n");
      out.write("    <div class=\"notes-column\">\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-check-circle section-icon\"></i>\r\n");
      out.write("            To-Do Items\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Today's Todos -->\r\n");
      out.write("        ");
 if (!todayTodos.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"time-section-header\">\r\n");
      out.write("                <i class=\"fas fa-sun\"></i> Today\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"task-grid\">\r\n");
      out.write("                ");
 for (ToDoItem todo : todayTodos) { 
      out.write("\r\n");
      out.write("                    <div class=\"task-card ");
      out.print( todo.isCompleted() ? "completed" : "" );
      out.write("\">\r\n");
      out.write("                        <div class=\"task-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editTodoItem(");
      out.print( todo.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( todo.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( todo.getDueDate() );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( todo.getPriority() );
      out.write(',');
      out.write(' ');
      out.print( todo.isCompleted() );
      out.write(")\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteTask(");
      out.print( todo.getId() );
      out.write(", 'todoitem')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-header\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"task-checkbox\" ");
      out.print( todo.isCompleted() ? "checked" : "" );
      out.write(" onchange=\"toggleComplete(");
      out.print( todo.getId() );
      out.write(", this.checked)\">\r\n");
      out.write("                            <div class=\"task-title ");
      out.print( todo.isCompleted() ? "completed" : "" );
      out.write('"');
      out.write('>');
      out.print( todo.getTitle() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-meta\">\r\n");
      out.write("                            <div class=\"task-time\">\r\n");
      out.write("                                <i class=\"fas fa-clock\"></i> ");
      out.print( timeFormat.format(todo.getDueDate()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"task-priority ");
      out.print( todo.getPriority() >= 8 ? "priority-high" : todo.getPriority() >= 5 ? "priority-medium" : "priority-low" );
      out.write("\">\r\n");
      out.write("                                P");
      out.print( todo.getPriority() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Tomorrow's Todos -->\r\n");
      out.write("        ");
 if (!tomorrowTodos.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"time-section-header\">\r\n");
      out.write("                <i class=\"fas fa-calendar-day\"></i> Tomorrow\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"task-grid\">\r\n");
      out.write("                ");
 for (ToDoItem todo : tomorrowTodos) { 
      out.write("\r\n");
      out.write("                    <div class=\"task-card ");
      out.print( todo.isCompleted() ? "completed" : "" );
      out.write("\">\r\n");
      out.write("                        <div class=\"task-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editTodoItem(");
      out.print( todo.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( todo.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( todo.getDueDate() );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( todo.getPriority() );
      out.write(',');
      out.write(' ');
      out.print( todo.isCompleted() );
      out.write(")\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteTask(");
      out.print( todo.getId() );
      out.write(", 'todoitem')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-header\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"task-checkbox\" ");
      out.print( todo.isCompleted() ? "checked" : "" );
      out.write(" onchange=\"toggleComplete(");
      out.print( todo.getId() );
      out.write(", this.checked)\">\r\n");
      out.write("                            <div class=\"task-title ");
      out.print( todo.isCompleted() ? "completed" : "" );
      out.write('"');
      out.write('>');
      out.print( todo.getTitle() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-meta\">\r\n");
      out.write("                            <div class=\"task-time\">\r\n");
      out.write("                                <i class=\"fas fa-clock\"></i> ");
      out.print( timeFormat.format(todo.getDueDate()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"task-priority ");
      out.print( todo.getPriority() >= 8 ? "priority-high" : todo.getPriority() >= 5 ? "priority-medium" : "priority-low" );
      out.write("\">\r\n");
      out.write("                                P");
      out.print( todo.getPriority() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Other Todos -->\r\n");
      out.write("        ");
 if (!otherTodos.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"time-section-header\">\r\n");
      out.write("                <i class=\"fas fa-calendar-alt\"></i> Other\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"task-grid\">\r\n");
      out.write("                ");
 for (ToDoItem todo : otherTodos) { 
      out.write("\r\n");
      out.write("                    <div class=\"task-card ");
      out.print( todo.isCompleted() ? "completed" : "" );
      out.write("\">\r\n");
      out.write("                        <div class=\"task-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editTodoItem(");
      out.print( todo.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( todo.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( todo.getDueDate() );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( todo.getPriority() );
      out.write(',');
      out.write(' ');
      out.print( todo.isCompleted() );
      out.write(")\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteTask(");
      out.print( todo.getId() );
      out.write(", 'todoitem')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-header\">\r\n");
      out.write("                            <input type=\"checkbox\" class=\"task-checkbox\" ");
      out.print( todo.isCompleted() ? "checked" : "" );
      out.write(" onchange=\"toggleComplete(");
      out.print( todo.getId() );
      out.write(", this.checked)\">\r\n");
      out.write("                            <div class=\"task-title ");
      out.print( todo.isCompleted() ? "completed" : "" );
      out.write('"');
      out.write('>');
      out.print( todo.getTitle() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-meta\">\r\n");
      out.write("                            <div class=\"task-time\">\r\n");
      out.write("                                <i class=\"fas fa-calendar\"></i> ");
      out.print( dateFormat.format(todo.getDueDate()) );
      out.write(' ');
      out.print( timeFormat.format(todo.getDueDate()) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"task-priority ");
      out.print( todo.getPriority() >= 8 ? "priority-high" : todo.getPriority() >= 5 ? "priority-medium" : "priority-low" );
      out.write("\">\r\n");
      out.write("                                P");
      out.print( todo.getPriority() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Empty State for Todos -->\r\n");
      out.write("        ");
 if (todoItems == null || todoItems.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <i class=\"fas fa-tasks fa-3x\"></i>\r\n");
      out.write("                <h3>No To-Do Items Yet</h3>\r\n");
      out.write("                <p>Create your first task to get started</p>\r\n");
      out.write("                <button class=\"btn btn-primary mt-3\" onclick=\"showAddModalType('todo')\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add To-Do Item\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Activities Column -->\r\n");
      out.write("    <div class=\"notes-column\">\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <i class=\"fas fa-calendar-check section-icon\"></i>\r\n");
      out.write("            Activities\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Today's Activities -->\r\n");
      out.write("        ");
 if (!todayActivities.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"time-section-header\">\r\n");
      out.write("                <i class=\"fas fa-sun\"></i> Today\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"task-grid\">\r\n");
      out.write("                ");
 for (Activity activity : todayActivities) { 
      out.write("\r\n");
      out.write("                    <div class=\"task-card activity-card\">\r\n");
      out.write("                        <div class=\"task-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editActivity(");
      out.print( activity.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( activity.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( activity.getDescription() != null ? activity.getDescription().replace("'", "\\'") : "" );
      out.write("', '");
      out.print( activity.getStartTime() );
      out.write("', '");
      out.print( activity.getEndTime() != null ? activity.getEndTime() : "" );
      out.write("')\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteTask(");
      out.print( activity.getId() );
      out.write(", 'activity')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-title\">");
      out.print( activity.getTitle() );
      out.write("</div>\r\n");
      out.write("                        ");
 if (activity.getDescription() != null && !activity.getDescription().trim().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"task-description\">");
      out.print( activity.getDescription() );
      out.write("</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"task-meta\">\r\n");
      out.write("                            <div class=\"task-time\">\r\n");
      out.write("                                <i class=\"fas fa-play\"></i> ");
      out.print( timeFormat.format(activity.getStartTime()) );
      out.write("\r\n");
      out.write("                                ");
 if (activity.getEndTime() != null) { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( timeFormat.format(activity.getEndTime()) );
      out.write("\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Tomorrow's Activities -->\r\n");
      out.write("        ");
 if (!tomorrowActivities.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"time-section-header\">\r\n");
      out.write("                <i class=\"fas fa-calendar-day\"></i> Tomorrow\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"task-grid\">\r\n");
      out.write("                ");
 for (Activity activity : tomorrowActivities) { 
      out.write("\r\n");
      out.write("                    <div class=\"task-card activity-card\">\r\n");
      out.write("                        <div class=\"task-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editActivity(");
      out.print( activity.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( activity.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( activity.getDescription() != null ? activity.getDescription().replace("'", "\\'") : "" );
      out.write("', '");
      out.print( activity.getStartTime() );
      out.write("', '");
      out.print( activity.getEndTime() != null ? activity.getEndTime() : "" );
      out.write("')\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteTask(");
      out.print( activity.getId() );
      out.write(", 'activity')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-title\">");
      out.print( activity.getTitle() );
      out.write("</div>\r\n");
      out.write("                        ");
 if (activity.getDescription() != null && !activity.getDescription().trim().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"task-description\">");
      out.print( activity.getDescription() );
      out.write("</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"task-meta\">\r\n");
      out.write("                            <div class=\"task-time\">\r\n");
      out.write("                                <i class=\"fas fa-play\"></i> ");
      out.print( timeFormat.format(activity.getStartTime()) );
      out.write("\r\n");
      out.write("                                ");
 if (activity.getEndTime() != null) { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( timeFormat.format(activity.getEndTime()) );
      out.write("\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Other Activities -->\r\n");
      out.write("        ");
 if (!otherActivities.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"time-section-header\">\r\n");
      out.write("                <i class=\"fas fa-calendar-alt\"></i> Other\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"task-grid\">\r\n");
      out.write("                ");
 for (Activity activity : otherActivities) { 
      out.write("\r\n");
      out.write("                    <div class=\"task-card activity-card\">\r\n");
      out.write("                        <div class=\"task-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" onclick=\"editActivity(");
      out.print( activity.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( activity.getTitle().replace("'", "\\'") );
      out.write("', '");
      out.print( activity.getDescription() != null ? activity.getDescription().replace("'", "\\'") : "" );
      out.write("', '");
      out.print( activity.getStartTime() );
      out.write("', '");
      out.print( activity.getEndTime() != null ? activity.getEndTime() : "" );
      out.write("')\">\r\n");
      out.write("                                <i class=\"fas fa-pencil-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" onclick=\"deleteTask(");
      out.print( activity.getId() );
      out.write(", 'activity')\">\r\n");
      out.write("                                <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"task-title\">");
      out.print( activity.getTitle() );
      out.write("</div>\r\n");
      out.write("                        ");
 if (activity.getDescription() != null && !activity.getDescription().trim().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"task-description\">");
      out.print( activity.getDescription() );
      out.write("</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"task-meta\">\r\n");
      out.write("                            <div class=\"task-time\">\r\n");
      out.write("                                <i class=\"fas fa-calendar\"></i> ");
      out.print( dateFormat.format(activity.getStartTime()) );
      out.write(' ');
      out.print( timeFormat.format(activity.getStartTime()) );
      out.write("\r\n");
      out.write("                                ");
 if (activity.getEndTime() != null) { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( timeFormat.format(activity.getEndTime()) );
      out.write("\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Empty State for Activities -->\r\n");
      out.write("        ");
 if (activities == null || activities.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check fa-3x\"></i>\r\n");
      out.write("                <h3>No Activities Yet</h3>\r\n");
      out.write("                <p>Schedule your first activity to get started</p>\r\n");
      out.write("                <button class=\"btn btn-primary mt-3\" onclick=\"showAddModalType('activity')\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add Activity\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Floating Add Button -->\r\n");
      out.write("<button class=\"floating-add-btn\" onclick=\"showAddTaskModal()\">\r\n");
      out.write("    <i class=\"fas fa-plus\"></i>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Task Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addTaskModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add New Task\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <button class=\"btn btn-primary w-100 mb-3\" onclick=\"showAddTodoModal()\">\r\n");
      out.write("                            <i class=\"fas fa-tasks d-block mb-2\"></i>\r\n");
      out.write("                            To-Do Item\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <button class=\"btn btn-primary w-100 mb-3\" onclick=\"showAddActivityModal()\">\r\n");
      out.write("                            <i class=\"fas fa-calendar-check d-block mb-2\"></i>\r\n");
      out.write("                            Activity\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Todo Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addTodoModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add To-Do Item\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"AddTaskServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"todoitem\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addTodoTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"addTodoTitle\" name=\"title\" placeholder=\"Task title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addTodoTime\" class=\"form-label\">Due Date & Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"addTodoTime\" name=\"dueDate\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addTodoPriority\" class=\"form-label\">Priority (1-10)</label>\r\n");
      out.write("                        <input type=\"number\" class=\"form-control\" id=\"addTodoPriority\" name=\"priority\" min=\"1\" max=\"10\" placeholder=\"5\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Add To-Do Item</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Activity Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"addActivityModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Add Activity\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"AddTaskServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"activity\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addActivityTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"addActivityTitle\" name=\"title\" placeholder=\"Activity title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addActivityDescription\" class=\"form-label\">Description</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"addActivityDescription\" name=\"description\" placeholder=\"Activity description\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addActivityStartTime\" class=\"form-label\">Start Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"addActivityStartTime\" name=\"startTime\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"addActivityEndTime\" class=\"form-label\">End Time (Optional)</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"addActivityEndTime\" name=\"endTime\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Add Activity</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Todo Item Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editTodoModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-edit me-2\"></i>Edit To-Do Item\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditTaskServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"editTodoId\" name=\"id\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"todoitem\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editTodoTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editTodoTitle\" name=\"title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editTodoDueDate\" class=\"form-label\">Due Date</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"editTodoDueDate\" name=\"dueDate\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editTodoPriority\" class=\"form-label\">Priority (1-10)</label>\r\n");
      out.write("                        <input type=\"number\" class=\"form-control\" id=\"editTodoPriority\" name=\"priority\" min=\"1\" max=\"10\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"editTodoCompleted\" name=\"completed\" value=\"true\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"editTodoCompleted\">\r\n");
      out.write("                                Mark as completed\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Save Changes</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit Activity Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editActivityModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">\r\n");
      out.write("                    <i class=\"fas fa-edit me-2\"></i>Edit Activity\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"EditTaskServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"editActivityId\" name=\"id\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"activity\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editActivityTitle\" class=\"form-label\">Title</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"editActivityTitle\" name=\"title\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editActivityDescription\" class=\"form-label\">Description</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"editActivityDescription\" name=\"description\" rows=\"3\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editActivityStartTime\" class=\"form-label\">Start Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"editActivityStartTime\" name=\"startTime\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"editActivityEndTime\" class=\"form-label\">End Time</label>\r\n");
      out.write("                        <input type=\"datetime-local\" class=\"form-control\" id=\"editActivityEndTime\" name=\"endTime\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Save Changes</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Include SweetAlert2 -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function showAddTaskModal() {\r\n");
      out.write("    new bootstrap.Modal(document.getElementById('addTaskModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showAddModalType(type) {\r\n");
      out.write("    if (type === 'todo') {\r\n");
      out.write("        showAddTodoModal();\r\n");
      out.write("    } else if (type === 'activity') {\r\n");
      out.write("        showAddActivityModal();\r\n");
      out.write("    } else {\r\n");
      out.write("        showAddTaskModal();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showAddTodoModal() {\r\n");
      out.write("    // Close the main add task modal if open\r\n");
      out.write("    const addTaskModal = bootstrap.Modal.getInstance(document.getElementById('addTaskModal'));\r\n");
      out.write("    if (addTaskModal) {\r\n");
      out.write("        addTaskModal.hide();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Set default time\r\n");
      out.write("    const now = new Date();\r\n");
      out.write("    now.setMinutes(now.getMinutes() - now.getTimezoneOffset());\r\n");
      out.write("    document.getElementById('addTodoTime').value = now.toISOString().slice(0, 16);\r\n");
      out.write("    \r\n");
      out.write("    new bootstrap.Modal(document.getElementById('addTodoModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showAddActivityModal() {\r\n");
      out.write("    // Close the main add task modal if open\r\n");
      out.write("    const addTaskModal = bootstrap.Modal.getInstance(document.getElementById('addTaskModal'));\r\n");
      out.write("    if (addTaskModal) {\r\n");
      out.write("        addTaskModal.hide();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Set default time\r\n");
      out.write("    const now = new Date();\r\n");
      out.write("    now.setMinutes(now.getMinutes() - now.getTimezoneOffset());\r\n");
      out.write("    document.getElementById('addActivityStartTime').value = now.toISOString().slice(0, 16);\r\n");
      out.write("    \r\n");
      out.write("    new bootstrap.Modal(document.getElementById('addActivityModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editTodoItem(id, title, dueDate, priority, completed) {\r\n");
      out.write("    document.getElementById('editTodoId').value = id;\r\n");
      out.write("    document.getElementById('editTodoTitle').value = title;\r\n");
      out.write("    document.getElementById('editTodoDueDate').value = dueDate.replace(' ', 'T').substring(0, 16);\r\n");
      out.write("    document.getElementById('editTodoPriority').value = priority;\r\n");
      out.write("    document.getElementById('editTodoCompleted').checked = completed;\r\n");
      out.write("    \r\n");
      out.write("    new bootstrap.Modal(document.getElementById('editTodoModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editActivity(id, title, description, startTime, endTime) {\r\n");
      out.write("    document.getElementById('editActivityId').value = id;\r\n");
      out.write("    document.getElementById('editActivityTitle').value = title;\r\n");
      out.write("    document.getElementById('editActivityDescription').value = description;\r\n");
      out.write("    document.getElementById('editActivityStartTime').value = startTime.replace(' ', 'T').substring(0, 16);\r\n");
      out.write("    if (endTime && endTime !== 'null') {\r\n");
      out.write("        document.getElementById('editActivityEndTime').value = endTime.replace(' ', 'T').substring(0, 16);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    new bootstrap.Modal(document.getElementById('editActivityModal')).show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteTask(id, type) {\r\n");
      out.write("    Swal.fire({\r\n");
      out.write("        title: 'Are you sure?',\r\n");
      out.write("        text: \"You won't be able to revert this!\",\r\n");
      out.write("        icon: 'warning',\r\n");
      out.write("        showCancelButton: true,\r\n");
      out.write("        confirmButtonColor: '#dc3545',\r\n");
      out.write("        cancelButtonColor: '#6c757d',\r\n");
      out.write("        confirmButtonText: 'Yes, delete it!'\r\n");
      out.write("    }).then((result) => {\r\n");
      out.write("        if (result.isConfirmed) {\r\n");
      out.write("            window.location.href = 'DeleteTaskServlet?id=' + id + '&type=' + type;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toggleComplete(id, isCompleted) {\r\n");
      out.write("    window.location.href = 'ToggleTaskServlet?id=' + id + '&completed=' + isCompleted;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
