/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-12-18 07:55:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import Models.Book;
import java.text.SimpleDateFormat;

public final class book_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/session.jsp", Long.valueOf(1750127333800L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Models.Book");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    boolean isLoggedIn = (session != null && session.getAttribute("isLoggedIn") != null) ?
                         ((Boolean) session.getAttribute("isLoggedIn")).booleanValue() : false;

    if (isLoggedIn == false || !isLoggedIn) {
        response.sendRedirect("login.jsp?message=not_logged_in");
        return;
    }
    
    int userId = (session.getAttribute("user_id") != null) ? (Integer) session.getAttribute("user_id") : 0; // Default ID, e.g., 0 or -1
    String username = (session.getAttribute("username") != null) ? (String) session.getAttribute("username") : "Guest";
    String email = (session.getAttribute("email") != null) ? (String) session.getAttribute("email") : "guest@example.com";
    String fullName = (session.getAttribute("full_name") != null) ? (String) session.getAttribute("full_name") : "Pengguna Tidak Dikenal";
    int roleId = (session.getAttribute("role_id") != null) ? (Integer) session.getAttribute("role_id") : 0; // Default role ID, e.g., 0 for unknown
    String roleName = (session.getAttribute("role_name") != null) ? (String) session.getAttribute("role_name") : "Guest";

      out.write(' ');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    ");

        Book book = (Book) request.getAttribute("book");
        ArrayList<Book> authorBooks = (ArrayList<Book>) request.getAttribute("authorBooks");
        
        if (authorBooks == null) authorBooks = new ArrayList<>();
        
        String bookTitle = book != null ? book.getTitle() : "Book Detail";
    
      out.write("\r\n");
      out.write("    <title>");
      out.print( bookTitle );
      out.write(" - Mugiwara Library</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"x-icon\" href=\"assets/images/Logo Store.png\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <div class=\"logo-container\">\r\n");
      out.write("                <a href=\"home\">\r\n");
      out.write("                    <img src=\"assets/images/Logo Store.png\" alt=\"logo\" class=\"logo_home\"> \r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category-search-container\">\r\n");
      out.write("                <div class=\"dropdown\">\r\n");
      out.write("                    <button class=\"btn dropdown-toggle category-button\" type=\"button\" id=\"dropdownMenuButton\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        <span id=\"categoryText\">Kategori</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                        <li class=\"category-search-li\"> \r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" placeholder=\"Cari Kategori...\" id=\"categorySearchInputInDropdown\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"books?category=Novel\">Novel</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"books?category=Majalah\">Majalah</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"books?category=Komik\">Komik</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"books\">Semua Kategori</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form class=\"form-inline flex-grow-1\" action=\"books\" method=\"get\"> \r\n");
      out.write("                    <div class=\"search-input-group\">\r\n");
      out.write("                        <input class=\"form-control search-input\" type=\"search\" name=\"query\" placeholder=\"Mau cari apa hari ini?\" aria-label=\"Search\">\r\n");
      out.write("                        <button class=\"search-btn\" type=\"submit\">\r\n");
      out.write("                            <i class=\"bi bi-search\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"user-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( isLoggedIn ? "cart" : "login.jsp" );
      out.write("\" class=\"text-white-icon me-3 position-relative\">\r\n");
      out.write("                    <img src=\"assets/images/cart.png\" alt=\"cart\" class=\"cart-icon\">\r\n");
      out.write("                    ");
 
                        Integer cartItemCount = (Integer) session.getAttribute("cartItemCount");
                        if (cartItemCount != null && cartItemCount > 0) {
                    
      out.write("\r\n");
      out.write("                    <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-dark\">\r\n");
      out.write("                        ");
      out.print( cartItemCount );
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" id=\"userMenuDropdown\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        <img src=\"assets/images/profile.png\" alt=\"profile\" class=\"profile-icon\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"userMenuDropdown\">\r\n");
      out.write("                        ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("                            <li><h6 class=\"dropdown-header\">Halo, ");
      out.print( fullName );
      out.write("</h6></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"profile.jsp\"><i class=\"bi bi-person-circle\"></i> Akun Saya</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"profile.jsp#transaksi\"><i class=\"bi bi-receipt\"></i> Pesanan</a></li>\r\n");
      out.write("                            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"logout.jsp\"><i class=\"bi bi-box-arrow-right\"></i> Logout</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"login.jsp\"><i class=\"bi bi-box-arrow-in-right\"></i> Login</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"register.jsp\"><i class=\"bi bi-person-plus-fill\"></i> Registrasi</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (book == null) { 
      out.write("\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"alert alert-danger\">\r\n");
      out.write("            <h4>Buku tidak ditemukan</h4>\r\n");
      out.write("            <p>Maaf, buku yang Anda cari tidak tersedia.</p>\r\n");
      out.write("            <a href=\"books\" class=\"btn btn-primary\">Kembali ke Daftar Buku</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Breadcrumb -->\r\n");
      out.write("    <div class=\"breadcrumb-container\">\r\n");
      out.write("        <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\" aria-label=\"breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb d-flex\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"home\"><strong>Home</strong></a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\" aria-current=\"page\">");
      out.print( book.getTitle() );
      out.write("</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Detail Buku -->\r\n");
      out.write("    <section class=\"container my-4\">\r\n");
      out.write("        <div class=\"book-detail-container\">\r\n");
      out.write("            <div class=\"d-flex flex-column align-items-center\">\r\n");
      out.write("                <img src=\"");
      out.print( book.getImagePath() != null ? book.getImagePath() : "default-book.jpg" );
      out.write("\" \r\n");
      out.write("                     alt=\"Cover ");
      out.print( book.getTitle() );
      out.write("\" class=\"book-detail-image\" />\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("                <form action=\"cart\" method=\"post\" class=\"mt-3\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"bookId\" value=\"");
      out.print( book.getBook_id() );
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"quantity\" value=\"1\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn-primary d-flex align-items-center justify-content-center gap-2\">\r\n");
      out.write("                        <strong>Tambah ke Keranjang</strong> \r\n");
      out.write("                        <i class=\"bi bi-cart fs-6\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\" class=\"btn-primary mt-3 d-flex align-items-center justify-content-center gap-2\">\r\n");
      out.write("                    <strong>Login untuk Membeli</strong> \r\n");
      out.write("                    <i class=\"bi bi-box-arrow-in-right fs-6\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Detail Buku -->\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("                <!-- Judul + Harga -->\r\n");
      out.write("                <div class=\"book-detail-header\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-start mb-2\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h3 class=\"fw-bold mb-1\">");
      out.print( book.getTitle() );
      out.write("</h3>\r\n");
      out.write("                            <div class=\"fw-bold text-danger small\">\r\n");
      out.write("                                by ");
      out.print( book.getAuthor() != null ? book.getAuthor().getName() : "Unknown Author" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"book-detail-price\">\r\n");
      out.write("                            <div class=\"h5 fw-bold\">Rp");
      out.print( String.format("%,d", book.getPrice()) );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"book-detail-section-title\">Detail Buku</div>\r\n");
      out.write("                <div class=\"book-meta-grid\">\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Penerbit</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">");
      out.print( book.getPublisher() != null ? book.getPublisher().getName() : "Unknown Publisher" );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Tanggal Terbit</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">\r\n");
      out.write("                            ");
 
                                if (book.getPublicationDate() != null) {
                                    SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
                                    out.print(sdf.format(book.getPublicationDate()));
                                } else {
                                    out.print("Tidak diketahui");
                                }
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">ISBN</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">");
      out.print( book.getISBN() != null ? book.getISBN() : "Tidak tersedia" );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Kategori</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">");
      out.print( book.getCategory() != null ? book.getCategory().getName() : "Tidak dikategorikan" );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Stok</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">\r\n");
      out.write("                            ");
 if (book.getStock() > 0) { 
      out.write("\r\n");
      out.write("                                <span class=\"text-success\">");
      out.print( book.getStock() );
      out.write(" tersedia</span>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <span class=\"text-danger\">Stok habis</span>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 if (book.getLength() > 0) { 
      out.write("\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Panjang</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">");
      out.print( book.getLength() );
      out.write(" cm</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    ");
 if (book.getWidth() > 0) { 
      out.write("\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Lebar</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">");
      out.print( book.getWidth() );
      out.write(" cm</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    ");
 if (book.getWeight() > 0) { 
      out.write("\r\n");
      out.write("                    <div class=\"book-meta-item\">\r\n");
      out.write("                        <div class=\"book-meta-label\">Berat</div>\r\n");
      out.write("                        <div class=\"book-meta-value\">");
      out.print( book.getWeight() );
      out.write(" gram</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("                <!-- Sinopsis -->\r\n");
      out.write("                <div class=\"book-detail-section-title\">Deskripsi Buku</div>   \r\n");
      out.write("                \r\n");
      out.write("                <p id=\"sinopsis\" class=\"book-synopsis synopsis-collapsed\">\r\n");
      out.write("                    ");
      out.print( book.getDescription() != null ? book.getDescription() : "Deskripsi tidak tersedia untuk buku ini." );
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("                <button id=\"toggleBtn\" class=\"toggle-synopsis-btn\">\r\n");
      out.write("                    <strong>Baca selengkapnya</strong>\r\n");
      out.write("                    <i id=\"toggleIcon\" class=\"bi bi-chevron-down ms-1\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>  \r\n");
      out.write("\r\n");
      out.write("    <!-- Author's Books -->\r\n");
      out.write("    ");
 if (!authorBooks.isEmpty() && book.getAuthor() != null) { 
      out.write("\r\n");
      out.write("    <section class=\"container my-5\">\r\n");
      out.write("        <div class=\"section-header\">\r\n");
      out.write("            <h4>Intip Karya ");
      out.print( book.getAuthor().getName() );
      out.write(" Lainnya...</h4>\r\n");
      out.write("            <p><a href=\"books?querya=");
      out.print( book.getAuthor().getAuthor_id() );
      out.write("\">Lihat Semua</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"authorBooks\" class=\"carousel slide book-carousel-container author-books-carousel\" data-bs-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                ");

                    int booksPerSlide = 6;
                    int slides = (int) Math.ceil((double) authorBooks.size() / booksPerSlide);
                    
                    for (int slide = 0; slide < slides; slide++) {
                        boolean isActive = slide == 0;
                
      out.write("\r\n");
      out.write("                <div class=\"carousel-item ");
      out.print( isActive ? "active" : "" );
      out.write("\">\r\n");
      out.write("                    <div class=\"book-list\">\r\n");
      out.write("                        ");

                            int startIndex = slide * booksPerSlide;
                            int endIndex = Math.min(startIndex + booksPerSlide, authorBooks.size());
                            
                            for (int i = startIndex; i < endIndex; i++) {
                                Book authorBook = authorBooks.get(i);
                                if (authorBook.getBook_id() != book.getBook_id()) { // Don't show current book
                        
      out.write("\r\n");
      out.write("                        <div class=\"book-card\">\r\n");
      out.write("                            <a href=\"books?action=detail&id=");
      out.print( authorBook.getBook_id() );
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("                                <img src=\"");
      out.print( authorBook.getImagePath() != null ? authorBook.getImagePath() : "default-book.jpg" );
      out.write("\" \r\n");
      out.write("                                     class=\"book-cover\" alt=\"");
      out.print( authorBook.getTitle() );
      out.write("\">\r\n");
      out.write("                                <div class=\"book-body\">\r\n");
      out.write("                                    <h6 class=\"book-author\">");
      out.print( authorBook.getAuthor() != null ? authorBook.getAuthor().getName() : "Unknown Author" );
      out.write("</h6>\r\n");
      out.write("                                    <p class=\"book-title\">");
      out.print( authorBook.getTitle() );
      out.write("</p>\r\n");
      out.write("                                    <strong class=\"book-price\">Rp");
      out.print( String.format("%,d", authorBook.getPrice()) );
      out.write("</strong>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 
                                }
                            } 
                        
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 if (slides > 1) { 
      out.write("\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#authorBooks\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#authorBooks\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"carousel-indicators\">\r\n");
      out.write("                ");
 for (int i = 0; i < slides; i++) { 
      out.write("\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#authorBooks\" data-bs-slide-to=\"");
      out.print( i );
      out.write("\" \r\n");
      out.write("                        ");
      out.print( i == 0 ? "class=\"active\" aria-current=\"true\"" : "" );
      out.write(" aria-label=\"Slide ");
      out.print( i + 1 );
      out.write("\"></button>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>  \r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2025 Isekai Byte - Mugiwara Library. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script>\r\n");
      out.write("        const sinopsis = document.getElementById(\"sinopsis\");\r\n");
      out.write("        const toggleBtn = document.getElementById(\"toggleBtn\");\r\n");
      out.write("        const toggleIcon = document.getElementById(\"toggleIcon\");\r\n");
      out.write("        \r\n");
      out.write("        if (sinopsis && toggleBtn && toggleIcon) {\r\n");
      out.write("            toggleBtn.addEventListener(\"click\", () => {\r\n");
      out.write("                const isCollapsed = sinopsis.classList.contains(\"synopsis-collapsed\");\r\n");
      out.write("                sinopsis.classList.toggle(\"synopsis-collapsed\", !isCollapsed);\r\n");
      out.write("                sinopsis.classList.toggle(\"synopsis-expanded\", isCollapsed);\r\n");
      out.write("                toggleBtn.querySelector(\"strong\").textContent = isCollapsed ? \"Sembunyikan\" : \"Baca selengkapnya\";\r\n");
      out.write("                toggleIcon.className = isCollapsed ? \"bi bi-chevron-up ms-1\" : \"bi bi-chevron-down ms-1\";\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
