/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-12-18 07:54:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Registrasi - Mugiwara Library</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"x-icon\" href=\"assets/images/Logo Store.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/izitoast@1.4.0/dist/css/iziToast.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"auth-container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"auth-card\">\r\n");
      out.write("        <a href=\"home\"><img src=\"assets/images/Logo Store.png\" alt=\"Mugiwara Library Logo\" class=\"auth-logo\"></a>\r\n");
      out.write("        <h2 class=\"auth-title\">Buat Akun Baru</h2>\r\n");
      out.write("        <p class=\"auth-subtitle\">Bergabunglah dengan komunitas pembaca kami</p>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"RegisterServlet\" method=\"post\" id=\"registerForm\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"fullName\" class=\"form-label\">Nama Lengkap</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"fullName\" name=\"fullName\" \r\n");
      out.write("                       placeholder=\"Masukkan Nama Lengkap Anda\" required \r\n");
      out.write("                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"100\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"email\" class=\"form-label\">Email</label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" \r\n");
      out.write("                       placeholder=\"email@contoh.com\" required \r\n");
      out.write("                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"100\">\r\n");
      out.write("                <div class=\"form-text\">Email akan digunakan untuk login ke akun Anda.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("                <div class=\"position-relative\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" \r\n");
      out.write("                           placeholder=\"Buat Password Anda\" required minlength=\"8\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-secondary position-absolute end-0 top-0 h-100\" \r\n");
      out.write("                            id=\"togglePassword\">\r\n");
      out.write("                        <i class=\"bi bi-eye\" id=\"eyeIcon\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-text\">\r\n");
      out.write("                    Password harus minimal 8 karakter, mengandung huruf besar, huruf kecil, angka, dan karakter khusus.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"password-strength mt-2\">\r\n");
      out.write("                    <div class=\"progress\" style=\"height: 6px;\">\r\n");
      out.write("                        <div class=\"progress-bar\" id=\"passwordStrength\" role=\"progressbar\" style=\"width: 0%\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small id=\"passwordStrengthText\" class=\"text-muted\"></small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"confirmPassword\" class=\"form-label\">Konfirmasi Password</label>\r\n");
      out.write("                <div class=\"position-relative\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"confirmPassword\" name=\"confirmPassword\" \r\n");
      out.write("                           placeholder=\"Konfirmasi Password Anda\" required>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-secondary position-absolute end-0 top-0 h-100\" \r\n");
      out.write("                            id=\"toggleConfirmPassword\">\r\n");
      out.write("                        <i class=\"bi bi-eye\" id=\"eyeIconConfirm\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"passwordMatch\" class=\"form-text\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <div class=\"form-check\">\r\n");
      out.write("                    <input class=\"form-check-input\" type=\"checkbox\" id=\"agreeTerms\" required>\r\n");
      out.write("                    <label class=\"form-check-label\" for=\"agreeTerms\">\r\n");
      out.write("                        Saya setuju dengan <a href=\"terms.jsp\" target=\"_blank\" class=\"auth-link\">Syarat dan Ketentuan</a> \r\n");
      out.write("                        serta <a href=\"privacy.jsp\" target=\"_blank\" class=\"auth-link\">Kebijakan Privasi</a>\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary w-100\" id=\"registerBtn\" disabled>\r\n");
      out.write("                <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <i class=\"bi bi-person-plus me-2\"></i>Daftar Sekarang\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"auth-footer\">\r\n");
      out.write("            Sudah punya akun? <a href=\"login.jsp\" class=\"auth-link\">Masuk disini</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/izitoast@1.4.0/dist/js/iziToast.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    document.getElementById('togglePassword').addEventListener('click', function() {\r\n");
      out.write("        togglePasswordVisibility('password', 'eyeIcon');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('toggleConfirmPassword').addEventListener('click', function() {\r\n");
      out.write("        togglePasswordVisibility('confirmPassword', 'eyeIconConfirm');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function togglePasswordVisibility(fieldId, iconId) {\r\n");
      out.write("        const passwordField = document.getElementById(fieldId);\r\n");
      out.write("        const eyeIcon = document.getElementById(iconId);\r\n");
      out.write("\r\n");
      out.write("        if (passwordField.type === 'password') {\r\n");
      out.write("            passwordField.type = 'text';\r\n");
      out.write("            eyeIcon.classList.remove('bi-eye');\r\n");
      out.write("            eyeIcon.classList.add('bi-eye-slash');\r\n");
      out.write("        } else {\r\n");
      out.write("            passwordField.type = 'password';\r\n");
      out.write("            eyeIcon.classList.remove('bi-eye-slash');\r\n");
      out.write("            eyeIcon.classList.add('bi-eye');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Password strength checker\r\n");
      out.write("    document.getElementById('password').addEventListener('input', function() {\r\n");
      out.write("        const password = this.value;\r\n");
      out.write("        const strengthBar = document.getElementById('passwordStrength');\r\n");
      out.write("        const strengthText = document.getElementById('passwordStrengthText');\r\n");
      out.write("\r\n");
      out.write("        let strength = 0;\r\n");
      out.write("        let feedback = [];\r\n");
      out.write("\r\n");
      out.write("        if (password.length >= 8) strength += 20;\r\n");
      out.write("        else feedback.push('minimal 8 karakter');\r\n");
      out.write("\r\n");
      out.write("        if (/[a-z]/.test(password)) strength += 20;\r\n");
      out.write("        else feedback.push('huruf kecil');\r\n");
      out.write("\r\n");
      out.write("        if (/[A-Z]/.test(password)) strength += 20;\r\n");
      out.write("        else feedback.push('huruf besar');\r\n");
      out.write("\r\n");
      out.write("        if (/[0-9]/.test(password)) strength += 20;\r\n");
      out.write("        else feedback.push('angka');\r\n");
      out.write("\r\n");
      out.write("        if (/[^A-Za-z0-9]/.test(password)) strength += 20;\r\n");
      out.write("        else feedback.push('karakter khusus');\r\n");
      out.write("\r\n");
      out.write("        strengthBar.style.width = strength + '%';\r\n");
      out.write("\r\n");
      out.write("        if (strength < 40) {\r\n");
      out.write("            strengthBar.className = 'progress-bar bg-danger';\r\n");
      out.write("            strengthText.textContent = 'Lemah - Perlu: ' + feedback.join(', ');\r\n");
      out.write("            strengthText.className = 'text-danger';\r\n");
      out.write("        } else if (strength < 80) {\r\n");
      out.write("            strengthBar.className = 'progress-bar bg-warning';\r\n");
      out.write("            strengthText.textContent = 'Sedang - Perlu: ' + feedback.join(', ');\r\n");
      out.write("            strengthText.className = 'text-warning';\r\n");
      out.write("        } else {\r\n");
      out.write("            strengthBar.className = 'progress-bar bg-success';\r\n");
      out.write("            strengthText.textContent = 'Kuat';\r\n");
      out.write("            strengthText.className = 'text-success';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        checkFormValidity();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Password match checker\r\n");
      out.write("    document.getElementById('confirmPassword').addEventListener('input', function() {\r\n");
      out.write("        const password = document.getElementById('password').value;\r\n");
      out.write("        const confirmPassword = this.value;\r\n");
      out.write("        const matchDiv = document.getElementById('passwordMatch');\r\n");
      out.write("\r\n");
      out.write("        if (confirmPassword === '') {\r\n");
      out.write("            matchDiv.textContent = '';\r\n");
      out.write("            matchDiv.className = 'form-text';\r\n");
      out.write("        } else if (password === confirmPassword) {\r\n");
      out.write("            matchDiv.innerHTML = '<i class=\"bi bi-check-circle text-success me-1\"></i>Password cocok';\r\n");
      out.write("            matchDiv.className = 'form-text text-success';\r\n");
      out.write("        } else {\r\n");
      out.write("            matchDiv.innerHTML = '<i class=\"bi bi-x-circle text-danger me-1\"></i>Password tidak cocok';\r\n");
      out.write("            matchDiv.className = 'form-text text-danger';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        checkFormValidity();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Add event listeners for other input fields to re-check validity\r\n");
      out.write("    document.getElementById('fullName').addEventListener('input', checkFormValidity);\r\n");
      out.write("    document.getElementById('email').addEventListener('input', checkFormValidity);\r\n");
      out.write("\r\n");
      out.write("    // Check form validity\r\n");
      out.write("    function checkFormValidity() {\r\n");
      out.write("        const fullName = document.getElementById('fullName').value;\r\n");
      out.write("        const email = document.getElementById('email').value;\r\n");
      out.write("        const password = document.getElementById('password').value;\r\n");
      out.write("        const confirmPassword = document.getElementById('confirmPassword').value;\r\n");
      out.write("        const agreeTerms = document.getElementById('agreeTerms').checked;\r\n");
      out.write("        const registerBtn = document.getElementById('registerBtn');\r\n");
      out.write("\r\n");
      out.write("        const isPasswordStrong = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z\\d]).{8,}$/.test(password);\r\n");
      out.write("        const isPasswordMatch = password === confirmPassword && confirmPassword !== '';\r\n");
      out.write("\r\n");
      out.write("        const isFullNameValid = fullName.trim() !== '';\r\n");
      out.write("        const isEmailValid = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);\r\n");
      out.write("\r\n");
      out.write("        registerBtn.disabled = !(isFullNameValid && isEmailValid && isPasswordStrong && isPasswordMatch && agreeTerms);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Terms checkbox listener\r\n");
      out.write("    document.getElementById('agreeTerms').addEventListener('change', checkFormValidity);\r\n");
      out.write("\r\n");
      out.write("    // Call checkFormValidity on page load to set initial button state\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', checkFormValidity);\r\n");
      out.write("\r\n");
      out.write("    // Form submission with loading state\r\n");
      out.write("    document.getElementById('registerForm').addEventListener('submit', function() {\r\n");
      out.write("        const submitBtn = document.getElementById('registerBtn');\r\n");
      out.write("        const spinner = submitBtn.querySelector('.spinner-border');\r\n");
      out.write("\r\n");
      out.write("        submitBtn.disabled = true;\r\n");
      out.write("        spinner.classList.remove('d-none');\r\n");
      out.write("        submitBtn.innerHTML = '<span class=\"spinner-border spinner-border-sm\" role=\"status\" aria-hidden=\"true\"></span> Memproses...';\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Show toast notifications\r\n");
      out.write("    ");
 if (request.getAttribute("toastType") != null) { 
      out.write("\r\n");
      out.write("        iziToast.");
      out.print( request.getAttribute("toastType") );
      out.write("({\r\n");
      out.write("            title: '");
      out.print( request.getAttribute("toastTitle") );
      out.write("',\r\n");
      out.write("            message: '");
      out.print( request.getAttribute("toastMessage") );
      out.write("',\r\n");
      out.write("            position: 'topRight',\r\n");
      out.write("            timeout: 5000\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("registrationSuccess") != null) { 
      out.write("\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("                window.location.href = 'login.jsp?message=registration_success&email=");
      out.print( request.getAttribute("registeredEmail") );
      out.write("';\r\n");
      out.write("            }, 2000);\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
