/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-26 14:42:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import models.Barang;
import config.JDBC;

public final class editbarang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("config.JDBC");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("models.Barang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Edit Barang</title>\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                background-color: #f8f9fa;\n");
      out.write("                padding-top: 20px;\n");
      out.write("            }\n");
      out.write("            .container {\n");
      out.write("                max-width: 800px;\n");
      out.write("                margin: 0 auto;\n");
      out.write("                background-color: white;\n");
      out.write("                padding: 30px;\n");
      out.write("                border-radius: 10px;\n");
      out.write("                box-shadow: 0 0 10px rgba(0,0,0,0.1);\n");
      out.write("            }\n");
      out.write("            .form-label {\n");
      out.write("                font-weight: 500;\n");
      out.write("            }\n");
      out.write("            .error-message {\n");
      out.write("                color: #dc3545;\n");
      out.write("                margin-top: 10px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            ");

                
                JDBC db = new JDBC();
                db.connect();
                
                // Ambil ID barang dari parameter URL
                String idParam = request.getParameter("id");
                Barang barang = new Barang();
                
                if (idParam != null && !idParam.isEmpty()) {
                    try {
                        int id = Integer.parseInt(idParam);
                        String query = "SELECT * FROM barang WHERE id_barang = " + id;
                        ResultSet rs = db.getData(query);
                        if (rs.next()) {
                            barang.setId(rs.getInt("id_barang"));
                            barang.setNama(rs.getString("nama_barang"));
                            barang.setKategori(rs.getString("kategori"));
                            barang.setHarga(rs.getDouble("harga"));
                            barang.setStok(rs.getInt("stok"));
                            barang.setDeskripsi(rs.getString("deskripsi"));
                        }
                       
                    } catch (NumberFormatException e) {
                        // Handle error
                    }
                }
                
                if (barang == null) {
            
      out.write("\n");
      out.write("                <div class=\"alert alert-danger\" role=\"alert\">\n");
      out.write("                    Barang tidak ditemukan. <a href=\"view.jsp\" class=\"alert-link\">Kembali ke daftar barang</a>\n");
      out.write("                </div>\n");
      out.write("            ");

                } else {
            
      out.write("\n");
      out.write("            <div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("                <h1>Edit Barang</h1>\n");
      out.write("                <div>\n");
      out.write("                    <a href=\"../index.jsp\" class=\"btn btn-outline-secondary me-2\">\n");
      out.write("                        <i class=\"bi bi-house-door\"></i> Beranda\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"view.jsp\" class=\"btn btn-outline-primary\">\n");
      out.write("                        <i class=\"bi bi-list-ul\"></i> Daftar Barang\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (request.getParameter("error") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-danger\" role=\"alert\">\n");
      out.write("                    Gagal mengupdate barang. Silakan coba lagi.\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <h1>Input Data Barang</h1>\n");
      out.write("            <form method=\"POST\" action=\"EditBarangServlet\">\n");
      out.write("                <input type=\"hidden\" id=\"nama\" name=\"idBarang\" value=\"");
      out.print( barang.getId());
      out.write("\" required /> <br />\n");
      out.write("                <label for=\"nama\">Nama Barang</label>\n");
      out.write("                <input type=\"text\" id=\"nama\" name=\"nama\" value=\"");
      out.print( barang.getNama() );
      out.write("\" required /> <br />\n");
      out.write("                <label for=\"nama\">Kategori</label>\n");
      out.write("                <input type=\"text\" id=\"nama\" name=\"kategori\" value=\"");
      out.print( barang.getKategori() );
      out.write("\" required /> <br />\n");
      out.write("                <label for=\"nama\">Harga</label>\n");
      out.write("                <input type=\"number\" id=\"nama\" name=\"harga\" value=\"");
      out.print( barang.getHarga() );
      out.write("\" required /> <br />\n");
      out.write("                <label for=\"nama\">Stok</label>\n");
      out.write("                <input type=\"number\" id=\"nama\" name=\"stok\" value=\"");
      out.print( barang.getStok() );
      out.write("\" required /> <br />\n");
      out.write("                <label for=\"nama\">Deskripsi</label>\n");
      out.write("                <input type=\"text\" id=\"nama\" name=\"deskripsi\" value=\"");
      out.print( barang.getDeskripsi());
      out.write("\" required /> <br />\n");
      out.write("                <input type=\"submit\" value=\"Simpan\" /> <br />\n");
      out.write("            </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <footer class=\"mt-5 text-center\">\n");
      out.write("                <p>&copy; 2025 Sistem Manajemen Barang</p>\n");
      out.write("            </footer>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
